### ISSUE TITLE
Support an @Expiry, @Expiration or @TTL annotation

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-data-couchbase#1060]
Just like we have `@Field` `@Id` and `@Version` support, it would be good to have a field to read the document expiry value from.

This field should support being of the type `int`, `long`, `Duration` and some subset of classes from `java.time.*`.

**Comment by aaronjwhiteside** [comment]
Being able to annotate a field to nominate it as containing the expiry value would also allow programmatic control of expiry when using a Repository.

```java
User user = new User();
user.setExpiry(Duration.ofHours(1));
userRepository.save(user);
```

Analogous to:
```java
template.insertById(User.class)
   .withExpiry(Duration.ofHours(1))
   .one(user);
```

**Comment by mikereiche** [comment]
Should be supported with #1149 by :
```
public interface UserRepository extends CouchbaseRepository<User, String>, DynamicProxyable<UserRepository> {...}
```
```
userRepository.withOptions(InsertOptions.insertOptions().expiry(Duration.ofHours(1)).save(user);
```

**Comment by aaronjwhiteside** [comment]
> userRepository.withOptions(InsertOptions.insertOptions().expiry(Duration.ofHours(1)).save(user);

So if the entity already has a field annotated with @Expiration, what is the purpose of specifying the expiry via options? Shouldn't we just read the value of the field?

This also opens up a can of worms around type conversion, what types does @Expiration support? 

I see long in the PR, but it would be nice if it supported things like `Instant` and `Duration`.
