### ISSUE TITLE
Field Mapping

### ISSUE THREAD

**Issue by haorancui94** [spring-projects/spring-data-couchbase#1068]
I want my `userId` in code to be  `user_id` field in document.
I was using the field to converting the field with 
```@Field(name = "user_id")```
but it won't work

instead if I use:
```@Field(value = "user_id")``` 
it will work

I know in the doc it told us to use ```@Field("user_id")```

But I check the code, might be the code has written in the opposite way that caused this problem?

```	
         /**
	 * The key to be used to store the field inside the document. Alias for {@link #name()}.
	 *
	 * @return an empty {@link String} by default.
	 */
	@AliasFor("name")
	String value() default "";

	/**
	 * The key to be used to store the field inside the document. Alias for {@link #value()}.
	 *
	 * @return an empty {@link String} by default.
	 */
	@AliasFor("value")
	String name() default "";
```

**Comment by mikereiche** [comment]
This does look a little weird and behave a little weird but it's the same as at least one other spring-data implementation.
I'll see if I can make all three forms do the same thing.

**Comment by mikereiche** [comment]
This change to BasicCouchbasePersistentProperty would change the usage of the Field annotation as desired:

	/**
	 * Returns the field name of the property.
	 * <p/>
	 * The field name can be different from the actual property name by using a custom annotation.
	 */
	String fieldName;
	@Override
	public String getFieldName() {
		if(fieldName != null ){
			return fieldName;
		}
		Field annotationField = getField().getAnnotation(Field.class);

		if (annotationField != null) {
			if (StringUtils.hasText(annotationField.value())) {
				return fieldName = annotationField.value();
			} else if (StringUtils.hasText(annotationField.name())) {
				return fieldName = annotationField.name();
			}
		}
		JsonProperty annotation = getField().getAnnotation(JsonProperty.class);

		if (annotation != null && StringUtils.hasText(annotation.value())) {
			return fieldName = annotation.value();
		}

		String fName = fieldNamingStrategy.getFieldName(this);

		if (!StringUtils.hasText(fName)) {
			throw new MappingException(String.format("Invalid (null or empty) field name returned for property %s by %s!",
					this, fieldNamingStrategy.getClass()));
		}

		return fieldName = fName;
	}
