### ISSUE TITLE
Enums can't be used as method parameters in Repository

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-data-couchbase#1069]
When I have the following classes:
```
enum Status { A,B }

@Document
class Entity { @Field Status status; }
```

I can write and read entities from the DB with no issues. However, when I create a function that would search for entities using status, it fails with 
```
com.couchbase.client.core.error.InvalidArgumentException: Unsupported type for JSON value: class Status
	at com.couchbase.client.java.json.JsonValue.coerce(JsonValue.java:94)
	at com.couchbase.client.java.json.JsonArray.add(JsonArray.java:178)
	at org.springframework.data.couchbase.core.query.QueryCriteria.maybeWrapValue(QueryCriteria.java:387)
```

Looking into the code, I see that `QueryCriteria` tries to convert Enum using `AbstractCouchbaseConverter.convertForWriteIfNeeded`. There it first looks converter up in `CouchbaseCustomConversions` but can't find it as conversions know about their own and parent converters only.
```
converters.addAll(DateConverters.getConvertersToRegister());
converters.addAll(CouchbaseJsr310Converters.getConvertersToRegister());

defaults.addAll(JodaTimeConverters.getConvertersToRegister());
defaults.addAll(Jsr310Converters.getConvertersToRegister());
defaults.addAll(ThreeTenBackPortConverters.getConvertersToRegister());
```

However, the actual conversion would be performed, if conversion found, by `conversionService` which is `DefaultConversionService` and this guy actually knows how to convert to and from Enum.

Adding custom implementations into `CouchbaseCustomConversions` solves this but I feel like it should not be necessary considering `DefaultConversionService` can do this already.

**Comment by mikereiche** [comment]
Thanks @edudar. I'll look at this when I get a chance.

**Comment by mstfymrtc** [comment]
Any progress on this? :/

**Comment by mikereiche** [comment]
It's in 4.2.0

https://github.com/spring-projects/spring-data-couchbase/commit/d16bbff4fe02710f8d13f354be4f36cf98aceefc

Also - it seems that using .toString() of the enum should work as well.

**Comment by mstfymrtc** [comment]
> It's in 4.2.0
> 
> [d16bbff](https://github.com/spring-projects/spring-data-couchbase/commit/d16bbff4fe02710f8d13f354be4f36cf98aceefc)
> 
> Also - it seems that using .toString() of the enum should work as well.

Yeah, it's a workaround i've used too. Thanks for the contribution <3

**Comment by vforchi** [comment]
I ran into the same problem, I upgraded to 4.2 but the problem is still there. I believe the reason is that I am using a List of enums, and this won't work
```
return this.conversions.getCustomWriteTarget(value.getClass()) //
				.map(it -> (Object) this.conversionService.convert(value, it)) //
				.orElseGet(() -> Enum.class.isAssignableFrom(value.getClass()) ? ((Enum<?>) value).name() : value);
```

**Comment by mikereiche** [comment]
@vforchi 

Collections and Arrays are handled by the calling code (and produce a CouchbaseList).  Can you show what issue you have? Maybe it is somewhere other than the converter?

		if (elementType == null || conversions.isSimpleType(elementType)) {
				target.put(getPotentiallyConvertedSimpleWrite(element));
			} else if (element instanceof Collection || elementType.isArray()) {
				target.put(writeCollectionInternal(asCollection(element), new CouchbaseList(conversions.getSimpleTypeHolder()),
						componentType));
			} else {

**Comment by mikereiche** [comment]
This is with 4.3-RC1, but 4.2.0 should have the same handling of an  array of  Enum

I add this to AirportRepository of the unit tests.

@ScanConsistency(query = QueryScanConsistency.REQUEST_PLUS)
Airport findByIataIn(Iata[] iata);
	

I add this to CouchbaseRepositoryQueryIntegrationTests.findByEnum()

Airport airport3 = airportRepository.findByIataIn( new Iata[]{Iata.vie, Iata.xxx});
assertNotNull(airport3, "should have found " + vie);
assertEquals(airport3.getId(), vie.getId());
			
Produces the n1ql:

SELECT META(`my_bucket`).id AS __id, META(`my_bucket`).cas AS __cas, `iata`, `icao`, `createdBy`, META(`my_bucket`).`expiration`, `size`, `someNumber` FROM `my_bucket` WHERE `_class` = "airport" AND `iata` in ( $1 )

**Comment by vforchi** [comment]
I will check, but I am using a collection, not an array.

**Comment by mikereiche** [comment]
The problem is reproducible with a Collection.  Fixing.

**Comment by mikereiche** [comment]
Making a new issue to handle collection arguments.  #1270

**Comment by jakubszybisty** [comment]
hey, looks like the query methods using collections of enum as a paremeter are still not working correctly. I created another issue https://github.com/spring-projects/spring-data-couchbase/issues/1855
tagging @mikereiche
