### ISSUE TITLE
Support for ARRAY_CONTAINS

### ISSUE THREAD

**Issue by cheeseq** [spring-projects/spring-data-couchbase#1073]
Hi! Do you have any plans for adding support of ARRAY_CONTAINS couchbase function for query criteria builder? It would be super useful to build a query like so `QueryCriteria.where("myArray").arrayContaining("myValue");`

**Comment by dpedroz** [comment]
I think it's not implemented properly. It's trying to use function `array_containing` which does not exist in db. Shouldn't the proper one be `array_contains`?
https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/arrayfun.html#fn-array-contains
