### ISSUE TITLE
AfterSaveEvent is never triggered

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-data-couchbase#1074]
`AbstractCouchbaseEventListener#onAfterSave` is never called

This worked in Spring Data Couchbase 3.x

**Comment by mikereiche** [comment]
maybeCallAfterSave() should be added to Reactive/CouchbaseTemplate and called from applyUpdatedCas() which is called from ReactiveInsert/Upsert/Replace one().

maybeCallBeforeSave() can be added and maybe called from the same place as maybeCallAfterConvert(). 

Or maybe the two could be called on their own in the Mono in the one() method.

**Comment by ocortassa** [comment]
Is there any updated on this issue?

We are getting the same issue on every event (onAfterDelete, onAfterSave, onApplicationEvent, onBeforeDelete, onBeforeConvert, onAfterSave).

Thanks

**Comment by mikereiche** [comment]
The prerequisite issue (#955) has been merged, so this can proceed.

**Comment by ocortassa** [comment]
Thank you @mikereiche, is there a defined timeline for releasing this feature?

**Comment by mikereiche** [comment]
Working on it now.
