### ISSUE TITLE
Custom N1ql reactive queries that return a collection does not work

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1077]
Hi

### Description

Custom n1ql **reactive** queries that return a collection(flux) are executing the **ReactiveFindByQueryOperationSupport.ReactiveFindByQuerySupport#one** method instead of the **ReactiveFindByQueryOperationSupport.ReactiveFindByQuerySupport#all** method.

This failure occurs because https://github.com/spring-projects/spring-data-couchbase/blob/5a55a79b1107bbedf82a26aec64adfc13e397a99/src/main/java/org/springframework/data/couchbase/repository/query/ReactiveN1qlRepositoryQueryExecutor.java#L77

 indicates that it is not a collection and execute https://github.com/spring-projects/spring-data-couchbase/blob/5a55a79b1107bbedf82a26aec64adfc13e397a99/src/main/java/org/springframework/data/couchbase/repository/query/ReactiveN1qlRepositoryQueryExecutor.java#L80 

instead of https://github.com/spring-projects/spring-data-couchbase/blob/5a55a79b1107bbedf82a26aec64adfc13e397a99/src/main/java/org/springframework/data/couchbase/repository/query/ReactiveN1qlRepositoryQueryExecutor.java#L78

_QueryMethod#isCollectionQuery_ is part of spring-data-commons

### Version
spring-data-couchbase 4.3.1 and spring-data-commons 2.4.3

### Sample

```java

public interface ReactiveEntitySamplePreparedQueryRepository extends ReactiveCouchbaseRepository<EntitySample, String> {

    @Query("#{#n1ql.selectEntity} WHERE #{#n1ql.filter}")
    Flux<EntitySample> findAllNoAnnotation();

}
```

How do you see it?

**Comment by mikereiche** [comment]
This was an issue in earlier release.   isCollectionQuery() needed to be overriden.

Please use the latest version of spring-data-couchbase which is 4.1.7
see https://forums.couchbase.com/t/flux-not-working-with-latest-spring-data-couchbase-4-1-2/29650/3

@Query("#{#n1ql.selectEntity} where #{#n1ql.filter} and iata = $1")
@ScanConsistency(query = QueryScanConsistency.REQUEST_PLUS)
Flux<Airport> getAllByIata(String iata);

vie = new Airport("airports::vie", "vie", "loww");
vie1 = new Airport("airports::vie1", "vie", "loww");
airportRepository.save(vie).block();
airportRepository.save(vie1).block();
List<Airport> airports0 = airportRepository.getAllByIata("vie").collectList().block();
assertEquals(2, airports0.size());

**Comment by mikereiche** [comment]
@jorgerod - Can I close those this issue?
