### ISSUE TITLE
revert 4.1.x to sdk 3.0.x

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1103]
revert 4.1.x to sdk 3.0.x to keep the minor revision unchanged within the spring-data minor revision.

**Comment by jorgerod** [comment]
Hi @mikereiche 

Is this change due to something specific or because of some incompatibility?

Thank you

**Comment by daschl** [comment]
@jorgerod the spring data core team (@mp911de) advised us to roll it back, because on each release train they want to keep the same minor version (only want to bump bigfixes of dependencies). This is to minimize friction with downstream components like spring-boot.

**Comment by daschl** [comment]
We keep the java-sdk breakage-free across minor versions, so if you need to bump it you can manually bump it in your pom file and it should just work as well.

**Comment by jorgerod** [comment]
Thank you for your prompt reply.

**Comment by mikereiche** [comment]
Some later versions of development 7.0 Cheshire Cat server require different urls for scopes and collections.  Using scopes and collections against those servers with 3.0.x will not work.
