### ISSUE TITLE
Update CI to Java 16

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-couchbase#1104]

**Comment by mikereiche** [comment]
see https://youtrack.jetbrains.com/issue/IDEA-263241 and https://github.com/rzwitserloot/lombok/issues/2681
(even if not using lombok and disabling the lombok plugin, the problem with lombok exists)

To compile in maven, this needs a number of --add-opens :

              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                    <fork>true</fork>
                    <compilerArgs>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                        <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.16</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

Intellij needs those as well as java.util :

--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED

Runtime -
```
for java.util.UUID and java.util.Optional
   --add-opens=java.base/java.util=ALL-UNNAMED
 for java.math.BigDecimal and BigInteger
  --add-opens=java.base/java.math=ALL-UNNAMED
 for java.lang.boolean, byte[], Integer
  --add-opens=java.base/java.lang=ALL-UNNAMED  
```

**Comment by mikereiche** [comment]
Previously had information from Mark in #1057.  Should do that instead of using jvm flags.
https://github.com/spring-projects/spring-data-couchbase/issues/1057

**Comment by mp911de** [comment]
Let's put this ticket on hold for now. Kotlin and Lombok still have compatibility issues and we can only continue here once both issues are resolved.

**Comment by mikereiche** [comment]
The issue with UUID still exists apart from Lombok/Intellij issues.
