### ISSUE TITLE
Support Prepared Statements

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1109]
Hi

I have been looking in the spring data couchbase documentation and reviewing the code and I have not found anything regarding [Prepared Statement](https://docs.couchbase.com/java-sdk/current/concept-docs/n1ql-query.html#prepared-statements-for-query-optimization) in a clean way.

I have seen that in `QueryOptions` there is the `adhoc` field but I don't know how to set the value in a correct way.

How do you recommend to do this case?

Thank you very much

**Comment by mikereiche** [comment]
#963 will support specifying QueryOptions for template and repository.

**Comment by mikereiche** [comment]
withOptions(queryOptions) now available in 4.3.0-M2
