### ISSUE TITLE
Delete N1QL query is deleting all documents instead of deleting only documents that matches the criteria

### ISSUE THREAD

**Issue by cheth83** [spring-projects/spring-data-couchbase#1131]
I have a simple requirement to delete all documents whose date is less than specified in the query. but whatever option I try, it’s deleting all documents from db. Code is written in Java Spring Boot project.  
versions:  
Sprinboot-2.4.4.   
spring data couchbase-4.1.6  
couchbase server: 6  

Sample codes I tried: I tried passing date argument as String, LocalDateTime, etc but none of it worked.
```
@Query("#{#n1ql.delete} WHERE #{#n1ql.filter} AND dateParam < MILLIS($1)")
void selectDateTime(LocalDateTime/String dateParam);

```
```
@Query("#{#n1ql.delete} WHERE #{#n1ql.filter} AND dateParam < $1")
void selectDateTime(String dateParam);
```

```
@Query("#{#n1ql.delete} WHERE #{#n1ql.filter} AND dateParam < MILLIS($1) #{#n1ql.returning}")
List selectDateTime(String dateParam);
```

dateParam passed as String was: “2021-04-07T06:47:32Z”
I also tried passing LocalDateTime- LocalDateTime.of(2021, 4, 7, 06, 47, 32);

To confirm there is nothing wrong in the criteria or data type or values I'm passing to above queries, I tried select query with same where clause and it's working perfectly fine - correct number of documents matching criteria is returned.

```
@Query("#{#n1ql.selectEntity} WHERE #{#n1ql.filter} AND syncTimeStamp < MILLIS($1)")
void selectDateTime(LocalDateTime/String date);
```

It’s surprising it’s working for select query but not for delete query.

If I run query from couchbase UI, it works fine - only documents that matches condition gets deleted.
`delete from DB_NAME where dateParam < 1618188052352`

Any help would be appreciated.

**Comment by thenoslav** [comment]
Hello, i had similar isssue. My query was:
```
@Query("#{#n1ql.delete} WHERE role IN $1 AND group = $2 AND `type` = \"#{T(com.something.service.persistance.entities.Rule).TYPE_DATABASE_LABEL}\" #{#n1ql.returning}")
List<Rule> deleteRulesByRoleAndGroup(JsonArray roles, String group);
```
This query has deleted all my documents in bucket (predicates was ignored).
I found out that when method name is starting with "delete", then it has been using ReactiveRemoveByQueryOperationSupport.assembleDeleteQuery() method for assembling query.
My query before this calling:
![image](https://user-images.githubusercontent.com/7026072/115892896-e968c680-a457-11eb-95b6-07edb23774d5.png)

and assembleDeleteQuery is returning:
![image](https://user-images.githubusercontent.com/7026072/115895991-47e37400-a45b-11eb-9375-ca5088930ade.png)

![image](https://user-images.githubusercontent.com/7026072/115896193-719c9b00-a45b-11eb-89cd-3fda5b1b62f0.png)

**Comment by mikereiche** [comment]
I'm investigating this.

**Comment by mikereiche** [comment]
override for toN1qlRemoveString() in StringQuery was missing.
