### ISSUE TITLE
org.springframework.data.annotation.Transient annotation doesn't work

### ISSUE THREAD

**Issue by Pradeeshbm** [spring-projects/spring-data-couchbase#1147]
I'm trying to ignore a field from being persisted in the couchbase DB using spring data @Transient annotation on the field. However, it doesn't work.

`
package com.example;

import java.util.List;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.springframework.data.annotation.Transient;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.With;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Person {

	@NotNull(message = "Name cannot be null")
	private String firstName;
	@NotBlank(message = "Last name cannot be blank")
	private String lastName;

	@Transient
	private List<Work> works;
}
`

**Comment by mikereiche** [comment]
I put a fix for this in #963.
