### ISSUE TITLE
question/issue about reading Object as JsonObject

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1156]
question/issue about reading object as JsonObject (instead of empty java.lang.Obect)
From Davide Pellegatta 

It’s about object mapping in spring-data-couchbase for very generic objects:
@Data
@With
@AllArgsConstructor
@NoArgsConstructor
@Document
public class Note {
	@Id
	private String id;
	private Map<String, Object> json;
}

basically my customer would like to work with something like this. I don’t think it’s possible to make it work. But I’d like to double check this
I already point them to CouchbaseTemplate for this, but at the same time I’d want to be sure as this with the mongo implementation works just fine.

**Comment by mikereiche** [comment]
Couchbase does not currently read it as it would need to assume that an Object is a map like this: (about line 353 in MappingCouchbaseConverter)
```
 	protected Map<Object, Object> readMap(final TypeInformation<?> type, final CouchbaseDocument source,
			final Object parent) 
.
.
.

			TypeInformation<?> valueType = type.getMapValueType();
			if (value instanceof CouchbaseDocument) {
				if (valueType.getType().equals(Object.class)) {
					map.put(key, readMap(type, (CouchbaseDocument) value, source));
				} else {
					map.put(key, read(valueType, (CouchbaseDocument) value, parent));
				}
```

**Comment by davidepellegatta** [comment]
Thank you Mike! do you think this is something worth adding or better go for a custom converter?

**Comment by mikereiche** [comment]
https://github.com/spring-projects/spring-data-couchbase/issues/1650 Added converters for JsonNode, JsonObject and JsonArray
