### ISSUE TITLE
Release 4.2.2   Delete non existent document throws  com.couchbase.client.core.error.DocumentNotFoundException

### ISSUE THREAD

**Issue by artiy1186** [spring-projects/spring-data-couchbase#1164]
I have recently upgraded to spring-data-couchbase 4.2.2. When using deleteById or delete  for a document which is not present, it throwsDocumentNotFoundException exception. 
With  spring-data-couchbase 3.2.13.RELEASE,  it was all fine (no exception) .

**Comment by mikereiche** [comment]
In version 3, all exceptions from remove() were ignored, making it impossible for the caller to know if the document had been deleted or not, or if the document did not exist.
In version 4, all exceptions from remove() are thrown. 
I understand this is different and will require a change in applications that wish to ignore remove() failures.  But at least this gives applications the choice of knowing whether the remove() worked or not.

**Comment by mikereiche** [comment]
Seems that the standard behavior for spring-data is to not throw an exception when document does not exist.

**Comment by achoice** [comment]
I got caught on this now also.
[https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#deleteById(ID)](url) clearly state _"If the entity is not found in the persistence store it is silently ignored."_ but spring-data-couchbase clearly violates that by throwing DataRetrievalFailureException.
