### ISSUE TITLE
Autoindexing fails if index field name contains '.'

### ISSUE THREAD

**Issue by vals-productions** [spring-projects/spring-data-couchbase#1166]
```java
@Document
@CompositeQueryIndex(name="AnotherEntity_idx", fields = {"anotherEntity.id"})
public class DatabaseEntity  {

private AnotherEntity anotherEntity;
....
}
```

Index generation will fail with the error:
```
Could not auto-create index with statement: CREATE INDEX idx_databasentity_anotherentity.id ON .....
```
note period '.' in index name. Apparently couchbase does not like it.

It probably could either replace '.' with '_' and/or, use index name provided in the annotation?

I can create the index manually through couchbase admin webapp if index name was acceptable.

The code is in CouchbasePersistentEntityIndexResolver createCompositeQueryIndexDefinitions method. As you cen see it appends field name and does not consider annotation index name.

```java

line 133: String indexName = "idx_" + StringUtils.uncapitalize(entity.getType().getSimpleName()) + "_" + fieldsIndexName;

```

**Comment by mikereiche** [comment]
Needs to replace '.' with '_'.  
Line 98 in CouchbasePersistentEntityIndexCreator

		StringBuilder statement = new StringBuilder("CREATE INDEX `").append(indexToCreate.getIndexName().replaceAll(".","_")).append("` ON `")
				.append(couchbaseOperations.getBucketName()).append("` (")
				.append(String.join(",", indexToCreate.getIndexFields())).append(")");

  And enclosing in back-ticks gives a better error message for invalid characters.
    "msg": "GSI CreateIndex() - cause: Invalid index name",
    "query": "CREATE INDEX `adv_meta_id.class` ON `my_bucket`(_class)"
