### ISSUE TITLE
 Support `project()` method for CouchbaseTemplate.findByQuery() queries

### ISSUE THREAD

**Issue by khanium** [spring-projects/spring-data-couchbase#1208]
Currently, CouchbaseTemplate.findById() has a method project( fieldnames array ) that allows filter fields to project for a findById query. 

**_Request_**
Add findByQuery().project() method for projecting only a given list of fields.

**Comment by khanium** [comment]
There is a .as(ClassType) that would allow do similar actions but it requires to define a projection class for that. It would be better also have project(array of string fieldnames) method

**Comment by mikereiche** [comment]
Thanks for your input. Is there such a feature in another spring data project we could follow?
Returning a Map<String,Object> might be a better result - all the data is not always String and also so the caller could know which Object was which property.

**Comment by AV25242** [comment]
Hello @khanium  `findByQuery().project(string[] )` should be made available with the next spring release
