### ISSUE TITLE
Exposing ObjectMapper disables Spring Boot JacksonAutoConfiguration

### ISSUE THREAD

**Issue by tchlyah** [spring-projects/spring-data-couchbase#1209]
Exposing ObjectMapper used by JsonSerializer implemented here: https://github.com/spring-projects/spring-data-couchbase/pull/1132, disables Spring Boot [JacksonAutoConfiguration#jacksonObjectMapper()](https://github.com/spring-projects/spring-boot/blob/253f98c3e7ae577618ca7d16d9116205f1fb4215/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L102), since it is annotated with `@ConditionalOnMissingBean`.

It forces usage of Couchbase ObjectMapper Bean which disables Spring Boot Jackson customizations (properties, modules, ...).

**Comment by mikereiche** [comment]
seems that removing the @Bean from couchbaseObjectMapper() would fix this.

**Comment by tchlyah** [comment]
Yes, is there any particular reason why we needed `@Bean` ?

**Comment by mikereiche** [comment]
The @Bean is to expose the objectMapper.   Is there some other way to do that?  I suppose a user could override the couchbaseObjectMapper() in their Config class as follows, but this looks really ugly.

static ObjectMapper theObjectMapper;

@override ObjectMapper couchbaseObjectMapper(){
        theObjectMapper = super.couchbaseObjectMapper();
        return theObjectMapper;
}

> which disables Spring Boot Jackson customizations (properties, modules, ...)

The purpose of exposing the ObjectMapper was to allow it to be customized.

**Comment by mikereiche** [comment]
Right. Not sure what I was thinking.

@override ObjectMapper couchbaseObjectMapper(){
theObjectMapper = super.couchbaseObjectMapper();
theObjectMapper... // customizations
return theObjectMapper;
}
