### ISSUE TITLE
Config timeout per operation

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1232]
Hi

Couchbase sdk allows to configure the timeout for each operation.

https://github.com/couchbase/couchbase-jvm-clients/blob/e87177e2569481cec12861a811b15a4ecee3a6af/java-client/src/main/java/com/couchbase/client/java/CommonOptions.java#L38

From spring-data-couchbase I don't see how to set this value. 
Is there any way to set timeouts for each operation?

Are there any plans to add it?

Thank you, very much

**Comment by mikereiche** [comment]
As of 4.3.0-M2, template operations have a withOptions(options) method,

`couchbaseTemplate.findById(User.class).withOptions(GetOptions.getOptions().timeout(Duration.ofSeconds(10))).one(id)`

 and for repositories, define the repository as:

`public interface AirportRepository extends CouchbaseRepository<Airport, String>, DynamicProxyable<AirportRepository>`

and then you can do :

```
Airport airport = airportRepository
					.withOptions(QueryOptions.queryOptions().timeout(Duration.ofSeconds(10)))
					.findByIata(vie.getIata());
```
