### ISSUE TITLE
Add `missing` and `valued` in repository method

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1237]
I would like to write these methods as part of a repository interface extending `CrudRepository`.

`List<Cat> findAllCatsWhereOwnerIsMissing();`
`List<Cat> findAllCatsWhereOwnerIsValued();`

Is it possible ?

**Comment by mikereiche** [comment]
IsEmpty -> is not valued

IsNotEmpty -> is valued

	List<Airport> findAllByIataIsEmpty();

SELECT META(`my_bucket`).id AS __id, META(`my_bucket`).cas AS __cas, `iata`, `icao`, `createdBy`, `size` FROM `my_bucket` WHERE `_class` = "airport" AND `iata` is not valued

**Comment by JesusTheHun** [comment]
Are those keywords specific to couchbase ?
You don't get the full precision of `MISSING` and `VALUED`, that's why they were created in the first place. `Empty` is vague.

**Comment by mikereiche** [comment]
The keywords - IsEmpty, IsNotEmpty (and all the others) come from spring-data-commons Part.Type.  Anything other than what is that list will result in the parser looking for a field in the entity class by that name. These are not (and can not) be product specific. 

https://github.com/spring-projects/spring-data-commons/blob/571cb36e31cb688b921b326826ee02af99520dd8/src/main/java/org/springframework/data/repository/query/parser/Part.java#L189 

> You don't get the full precision of MISSING and VALUED

spring-data-couchbase translates "IsEmpty" to 'is not valued'  It's the last predicate in the query in the example. Likewise, IsNotEmtpy translates to 'is valued'.  

> SELECT META(my_bucket).id AS __id, META(my_bucket).cas AS __cas, iata, icao, createdBy, size FROM my_bucket WHERE _class = "airport" AND iata is not valued

spring-data-couchbase translates "Exists" to 'is not missing'. Unfortunately, there is no 'NotExists', and no extra Part.Tree types, so no means to use 'is missing'.  Maybe there is some combination of other operators that give the same result?

https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java

https://github.com/spring-projects/spring-data-couchbase/blob/main/src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
