### ISSUE TITLE
Pageable SpEL Context Extension

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1238]
When writing a custom query using `@Query` we can use `#{#n1ql.selectEntity}`, it would be nice to have `#{#n1ql.pageable} ` and accept a `Pageable` parameter. I would look like this :

```java
@Query("#{#n1ql.selectEntity} WHERE complexCondition = $1 #{#n1ql.pageable} ")
Page<MyEntity> myFunction(boolean isComplex, Pageable pageable);
```

Edit : I know that `#{#n1ql.filters}` can work but it also add the `_class` filter, which may not be wanted in some cases.
Edit 2 : See
- https://github.com/spring-projects/spring-data-couchbase/issues/577
- https://github.com/spring-projects/spring-data-couchbase/pull/128

**Comment by mikereiche** [comment]
no #{#n1ql.pageable} is required.  The OFFSET and LIMIT are appended based on the existence of the Pageable parameter.

```
@Query("#{#n1ql.selectEntity} WHERE iata = $1")
Page<Airport> myFunction(String iata, Pageable pageable);
```
```	
Pageable page=  PageRequest.of(2, 3);
Page<Airport> airports = airportRepository.myFunction("vie", page);
```
gives:
``` 
SELECT META(`my_bucket`).id AS __id, META(`my_bucket`).cas AS __cas, `_class`, `iata`, `icao`, `createdBy`, META(`my_bucket`).`expiration`, `size`, `someNumber` FROM `my_bucket` WHERE iata = $1 LIMIT 3 OFFSET 6
```
