### ISSUE TITLE
@Field name not used for repository method

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1247]
Still migrating our app to Spring Data Couchbase 4, we have the following situation :

```java
@Document
@Data
public class Foo extends AbstractAuditingEntity<Foo> implements Serializable {
    @Field("some_prop")
    private String someProp;
}

@Repository
public interface FooRepository extends CouchbaseRepository<Foo, String> {
    List<Foo> findBySomeProp(String someProp);
}
```

When I call `fooRepository.findBySomeProp(...)` the result is an empty entity except for the id and the audit fields.
I dug down and I found out that `ReactiveFindByQueryOperationSupport.all(...)` assembled query is : 

```sql
SELECT META(`acme`).id AS __id, META(`acme`).cas AS __cas, `prefix`, `someProp`, `revision`, `createdById`, `createdDate`, `lastModifiedById`, `lastModifiedDate` FROM `acme` WHERE `_class` = "acme.domain.Foo" AND `some_prop` = $1
```

As you can see the field is correct in the `WHERE` clause but not in the `SELECT`.
Therefore the returned object is mostly empty, all business properties are `null`.

Did we forget to configure something ? Native methods works well.

**Comment by mikereiche** [comment]
That's a bug that has been fixed - but maybe only in 4.3.0-M3. What version do you have?   I'll investigate later today.
