### ISSUE TITLE
Repositories ignore the query scan consistency set in the CouchbaseTemplate's.

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-data-couchbase#1273]
I can see that at some point a `getDefaultConsistency()` method was added to the `AbstractCouchbaseConfiguration` that's used to drive the configuration of the underlying `CouchbaseTemplate`'s.

The problem is that it does not actually get applied correctly to Repositories, because of the code in `SimpleCouchbaseRepository`:

```java
	private QueryScanConsistency buildQueryScanConsistency() {
		QueryScanConsistency scanConsistency = QueryScanConsistency.NOT_BOUNDED;
		if (crudMethodMetadata.getScanConsistency() != null) {
			scanConsistency = crudMethodMetadata.getScanConsistency().query();
		}
		return scanConsistency;
	}
```

If no `@ScanConsistency` annotation was found, it defaults to `QueryScanConsistency.NOT_BOUNDED`, which explicitly overrides whatever the default is in the CouchbaseTemplate. 

This relates to issue: https://github.com/spring-projects/spring-data-couchbase/issues/1062

**Comment by mikereiche** [comment]
See the notes from Oct 18 on https://github.com/spring-projects/spring-data-couchbase/issues/1243 

https://github.com/spring-projects/spring-data-couchbase/blob/4.2.x/src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java

https://github.com/spring-projects/spring-data-couchbase/blob/4.2.x/src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java

**Comment by aaronjwhiteside** [comment]
Ah thanks, I was one minor point release behind :)
