### ISSUE TITLE
Expose some private methods of the template and repository

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1310]
Hello

Both **repositories** and **templates** are **extensible** but I have found several private methods that I would need to be able to extend efficiently. 

- https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryBase.java#L71
- https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryBase.java#L86
- https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java#L168
-  In the classes `ExecutableXXXOperationSupport` and `ReactiveXXXOperationSupport` there are classes with the constructor not visible and others with the public constructor. I think that the ideal would be that all of them have the public constructor to be able to extend and to be able to customize some operation. 
Sample:
https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/core/ReactiveExistsByIdOperationSupport.java#L40
https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java#L41

Something similar was done on this issue: 
- #1210 

What do you think?

Thanks in advance

**Comment by mikereiche** [comment]
Isn't 'protected' sufficient for accessing with a subclass?

Can you give an example of what you are wanting to do?

**Comment by jorgerod** [comment]
Hi @mikereiche 

With _protected_ would be perfect but they are with _default visibility_ (only accessible within the package).

**Comment by mikereiche** [comment]
"there are classes with the constructor not visible and others with the public constructor. "

I believe the constructors are/should be only called by corresponding method in Reactive/CouchbaseTemplate and none of them need to be public.  Can you explain the case where they would need to be public?  Can you explain the case where you would need getScope() and getCollection() to be public?

	@Override
	public <T> ReactiveInsertById<T> insertById(Class<T> domainType) {
		return new ReactiveInsertByIdOperationSupport(this).insertById(domainType);
	}

**Comment by jorgerod** [comment]
Hi

I would need that `getScope()` and `getCollection()` to be **protected**.

For example, I extends `SimpleCouchbaseRepository` for override method save (add operation insert)

```java
public class CouchbaseBaseRepository<T> extends SimpleCouchbaseRepository<T, String> {

	@Override
	@SuppressWarnings("unchecked")
	public <S extends T> S save(S entity) {
		Assert.notNull(entity, "Entity must not be null!");
		// if entity has non-null, non-zero version property, then replace()
		S result;
		if (hasNonZeroVersionProperty(entity, operations.getConverter())) {
		     result = (S) operations.replaceById(getJavaType()).inScope(getScope()).inCollection(getCollection()).one(entity);
		} else {
		     result = (S) operations.upsertById(getJavaType()).inScope(getScope()).inCollection(getCollection()).one(entity);
		}  else {
                   //Creating new document
                    result = (S) operations.insertById(getJavaType()).inScope(getScope()).inCollection(getCollection()).one(entity);
               }
		return result;
	}
```


On the other hand, I also extend the template by adding another operation and it would be very useful to use the method 

- https://github.com/spring-projects/spring-data-couchbase/blob/6e3c6267f79dc79465b0c1e0aaa67727fa3d32fc/src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java#L168

Thank you very much

**Comment by mikereiche** [comment]
Ok - that code isn't even going to compile with the two consecutive else's without if's .
If this is to work-around https://github.com/spring-projects/spring-data-couchbase/issues/1277, please just submit a PR according to the issue.

> I also extend the template by adding another operation 

But why?

**Comment by mikereiche** [comment]
>  have added the touch operation...

getAndTouch is already present - see https://github.com/spring-projects/spring-data-couchbase/issues/982

> saving with the possibility of the insertById

insertById will be fixed with  see https://github.com/spring-projects/spring-data-couchbase/issues/982.

We're not going to open up APIs to work-around bugs instead of fixing bugs.

Can you create a PR for the addition of Subdocument support?

Thanks.
