### ISSUE TITLE
OptimisticLockingFailureException is not thrown by spring-data-couchbase but according to the documentation it should be thrown

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1314]
Hi

`OptimisticLockingFailureException` is not thrown by spring-data-couchbase but according to the documentation it should be thrown

![image](https://user-images.githubusercontent.com/5095855/151955516-d037e6a9-034a-4e6a-80b8-76e0fdc00fd0.png)

Instead it is throwing `DataIntegrityViolationException` caused by `CasMismatchException`.

https://github.com/spring-projects/spring-data-couchbase/blob/7e45fa24a1ab790d5fd308069a0c886ed3f37f8f/src/main/java/org/springframework/data/couchbase/core/CouchbaseExceptionTranslator.java#L69-L73

Is there an error in the documentation?

Related issue: #944 #934

**Comment by mikereiche** [comment]
Looks like they don't match.
