### ISSUE TITLE
FindByXXX fails to work with field marked as Id

### ISSUE THREAD

**Issue by shaniiwild** [spring-projects/spring-data-couchbase#1321]
Hi!
Before the upgrade to Spring Data 4.3 we had the following derived query working fine:
![image](https://user-images.githubusercontent.com/58590145/152307697-559e10ee-02c3-45dd-9100-bac701c23605.png)

The find by was accessing this field with the name 'key' which is marked as Id by annotation and results were retrieves as expected.
![image](https://user-images.githubusercontent.com/58590145/152307133-485d2612-9ce2-4fef-b32a-a83f80f69ac2.png)
(Please note: It worked without n1ql implementation)

Following the upgrade, derived methods which **are approaching field marked with @id** failed to retrieve results (Also with combination of another fields, For example: findByKeyAndStatus()).
We solved it using CrudRepository inherited method of findById() 
But We would still like to understand what has changed that it's now fails to work? is it a bug?
Thanks.

**Comment by mikereiche** [comment]
Thanks. Roi told me of the issue and I was not able to reproduce it.  Please provide everything needed to reproduce it  -  the implementation of FileHeader and the repository and the code that calls findByKey.

btw - I believe you should be using the findById method which uses the kv API. It will be about 10x  faster than the query API that findByKey uses.

**Comment by mikereiche** [comment]
spring-data-couchbase does not store the @Id property in the document. It stores it only as the document id and in a query can be referenced by meta(`bucket`).id   Derived queries should have references to "key" replaced with meta(`bucket`).id

**Comment by mikereiche** [comment]
Please also provide the document that was to be retrieved.

**Comment by mikereiche** [comment]
If there is a constructor that has a 'key' argument, and that argument is ignored in the constructor (i.e. because the id is @Generated), then the 'key' field in the class will not be populated from meta().id on find operations, thus a subsequent findByKey(found.getKey()) will not return anything because getKey() returned null because it was not set in the constructor.
So there are all kinds of things that could occur, which is why I need to be able to run a reproducer in the debugger to see what is going on. But given the description here and assuming that nothing else is out of the ordinary - I'm not able to reproduce the issue.  Is FileHeader an abstract class or interface, perhaps? That would prevent any non-@Query methods from returning results - see #1315.

**Comment by shaniiwild** [comment]
Hi @mikereiche  
Sorry for the late response.
I understand from you comments that it's better performance to use findById. 
It's fine, However we have cases where we search for multiple fields (for example findByKeyAndStatus) and in order to overcome this issue we had to implement the query in n1ql.

I understand from your comment there could be some explanations for this issue.  Also wanted to clarify again that it did work before we switched to new spring data and defined collections. So here are the details, Please let us know if we need to implement some adjustment for it to work again.
**File header**
![image](https://user-images.githubusercontent.com/58590145/152955114-0646e249-dbcb-463d-a69d-a25bb1b1ae26.png)
**Class inherits from abstract Couchbase entity class:**
![image](https://user-images.githubusercontent.com/58590145/152955244-115e7fa6-a7f3-47ff-ac17-dce4da41450d.png)
**The derived method in repository:**
![image](https://user-images.githubusercontent.com/58590145/152955406-517f00e3-6e1e-4247-b20c-19f7f0da1463.png)

Thanks alot!

**Comment by mikereiche** [comment]
Can you please provide the actual text of those classes (instead of screen-shots) so I don't have to type it in and worry about typos? Thanks.

**Comment by shaniiwild** [comment]
@mikereiche  Thanks a lot for all the effort.
