### ISSUE TITLE
@N1qlJoin and couchbase collections

### ISSUE THREAD

**Issue by martin8877** [spring-projects/spring-data-couchbase#1325]
Does `@N1qlJoin` work with entities annotated with `@Collection`? 
I tried simple join of two entities `@N1qlJoin(on = "lks.rightEntityId=meta(rks).id")` (lks is in different collection than rks) and it does not work. An exception is thrown: `Keyspace not found in CB datastore`. It looks like the default collection is used.

**Comment by mikereiche** [comment]
Hi @martin8877 - can you post the repository class , the entity class and the code that calls it ? Thanks
