### ISSUE TITLE
Cache Eviction not working

### ISSUE THREAD

**Issue by the-wrangler17** [spring-projects/spring-data-couchbase#1369]
Cache eviction is not taking into account the scope and collection, only the bucket. The problem seems to be in the DefaultCouchbaseCacheWriter.clear(String) method.

public long clear(final String pattern) {
    QueryResult result = clientFactory.getCluster().query(
		"DELETE FROM `" + clientFactory.getBucket().name() + "` where meta().id LIKE $pattern",
		queryOptions().metrics(true).parameters(JsonObject.create().put("pattern", pattern + "%")));
    return result.metaData().metrics().map(QueryMetrics::mutationCount).orElse(0L);
}

**Comment by mikereiche** [comment]
the cacheEvict test case does not check that user1 is evicted. Only that user2 is not evicted.

	@Test
	void cacheEvict() {
		CacheUser user1 = new CacheUser(UUID.randomUUID().toString(), "first1", "last1");
		CacheUser user2 = new CacheUser(UUID.randomUUID().toString(), "first2", "last2");
		cache.put(user1.getId(), user1); // put user1
		cache.put(user2.getId(), user2); // put user2
		cache.evict(user1.getId()); // evict user1
		assertEquals(user2, cache.get(user2.getId()).get()); // get user2 -> present
	}
