### ISSUE TITLE
Spring Data Couchbase find from replica issue

### ISSUE THREAD

**Issue by projectpandm** [spring-projects/spring-data-couchbase#1375]
[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)

We are planning to use Spring Data Couchbase but stuck at the lack of support towards querying replica nodes.

Going by the docs, I see that one has to use couchbaseTemplate to query on replica nodes. But I see that we need to do lot of redundant code to achieve this. Say I have a Spring repository method  like this below.
`@Query("#{#n1ql.selectEntity} WHERE role = 'admin' AND #{#n1ql.filter}")
List<UserInfo> findAllAdmins();`

If I have to retry this method using Couchbase Template, then one has to prepare a new Query object. The above Spring SpEL defined query is of no use while retrying using couchbaseTemplate.
`SampleTemplate.findByQuery(entityClass).matching(new N1QLQuery())`

So a developer has to frame two versions of Query to achieve this read from replica nodes use case ?

**Comment by mikereiche** [comment]
What is the case where this would be useful and appropriate, and how would you suggest it be implemented?

**Comment by mikereiche** [comment]
After some thought on this - when a node becomes unavailable, there is a short time (seconds?) where the client and other nodes are not aware that the node is unavailable.  After that - kv requests to the unavailable node are sent to the replica node.  As for query requests - they are 'fanned out' to all the query nodes and predicates on indexed fields return the matching  keys - which are used in a kv operation to retrieve the document.  If the primary node for a given key is not available, the kv request should get the document from a replica.   So you should not need to manually redirect a query.  Let me know if you find this is not the case.

**Comment by projectpandm** [comment]
Sure... I will try to replicate this scenario in my local and will let you know. 
Acc to you, SDK itself will send the requests to the available nodes when a primary node is not available.

One other use case where we need reads from replica in our use case is:
There are multiple jobs that will perform writes on couchbase that we are connecting. Its not guaranteed that they will write on the primary node. 

So sometimes it is possible that simply that data is not yet available in the primary node.
