### ISSUE TITLE
QueryDSL support introduced mandatory dependency on querydsl

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-data-couchbase#1387]
#1288 introduced querydsl and added the querydsl-apt dependency as a transitive dependency in the compile scope.

This was [discussed in a review comment](https://github.com/spring-projects/spring-data-couchbase/pull/1330/files#r828328011) by @mp911de but it looks like this was not applied.

Currently this is blocking both spring-projects/spring-boot#30634 and spring-projects/spring-boot#30610

**Comment by mikereiche** [comment]
Looking...
