### ISSUE TITLE
Annotation APIs should not have compile scope

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-data-couchbase#1400]
Support of QueryDSL has moved `annotation-api` to compile scope, see https://github.com/spring-projects/spring-data-couchbase/commit/c288d053c94cb68121a63395bde7410b1894ece7#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L163

I don't think it should be a mandatory dependency of this module. Shouldn't it be provided instead? Noticed with `4.4.0-RC1`

**Comment by mikereiche** [comment]
It seems I can remove the dependency completely from pom.xml in 4.4.x - is that the correct change? It is not present in the 5.x/main branch.
