### ISSUE TITLE
On version 4.2.3 count no longer works as expected

### ISSUE THREAD

**Issue by JacCas2014** [spring-projects/spring-data-couchbase#1420]
SELECT COUNT(1) > 0, "xxx" AS __id, 0 AS __cas
FROM #{#n1ql.bucket} 
WHERE #{#n1ql.filter} AND data.id= $1.

which previously returned a Boolean now returns the key with 'xxx' and an empty data item.

Also have to add 'GROUP BY data.id' or always returns the key 'xxx' and an empty data item, even when there is no matching data.

**Comment by mikereiche** [comment]
Hi  @JacCas2014  - there was a change to determine how to handle a query by looking for "count("  in the (lowercased) query string. That change probably needs to be backed-out.  What's the method name used for this query?

**Comment by JacCas2014** [comment]
@Query("SELECT COUNT(1) > 0, "xxx" AS __id, 0 AS __cas
FROM #{#n1ql.bucket}
WHERE #{#n1ql.filter} AND data.id= $1.")
Mono<Boolean> isPresent(String id)

**Comment by JacCas2014** [comment]
Called by:
public Mono<Boolean> isPresent(String id) {
return this.repo.isPresent(id);
}

**Comment by mikereiche** [comment]
Thanks.  I can see that you posted `Mono<Boolean>`

**Comment by mikereiche** [comment]
Ok - I have tested and verified this issue as being preset in 4.2.x and am investigating.
It no longer exists in the latest published version - 4.3.4.  Is it possible for you to use 4.3.4?

**Comment by JacCas2014** [comment]
Thanks for looking into it. I'll look to upgrade.

**Comment by mikereiche** [comment]
The issue in 4.2.3 is that there is no support for queries that return a simple type (like Boolean), other than for 'count' queries.

**Comment by mikereiche** [comment]
Closing as already fixed.
