### ISSUE TITLE
Ignore case queries don't work

### ISSUE THREAD

**Issue by ilyavy** [spring-projects/spring-data-couchbase#1421]
If we have an entity, e.g. city:
```
{
  "name": "New York"
}
```
And we try to find it, ignoring case with the following repository method:
```
@Repository
public interface CityRepo extends ReactiveCouchbaseRepository<City, String> {
    Flux<City> findByNameIgnoreCase(String name);
}
```
It generates the following query:
```
Created query  WHERE `name` = "NEW YORK" for * fields.
```
And consequently doesn't find the existing city entity with the name "New York".

**Comment by mikereiche** [comment]
This is correct. It's not implemented.

**Comment by ilyavy** [comment]
Probably, it is worth to reflect it in the documentation, since now the docs inherit common spring-data docs, and there is stated that it should work. If I looked at correct place at least.

**Comment by ilyavy** [comment]
https://github.com/spring-projects/spring-data-couchbase/commit/62feffa89d2264e1fdfdb9913703f4f106a7d60b closes this issue
