### ISSUE TITLE
[Feature Request] USE_METHOD strategy for id generation

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1443]
It would be nice to be able to use a method to generate the id instead of either the UUID or a set of attributes.

**Comment by mikereiche** [comment]
There could be an extension to the @Generated annotation/converter to do that.

Otherwise, the id can be generated by any means and then set in the entity before conversion.

**Comment by JesusTheHun** [comment]
> Otherwise, the id can be generated by any means and then set in the entity before conversion.

Of course, we could do the same instead of using `USE_ATTRIBUTES`, it's just not convenient.
