### ISSUE TITLE
fix typo in cache documentation where it has catch.invalidate() instead of cache.invalidate()

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1525]

**Comment by BKaneAtWork** [comment]
On this same line in the docs, please also change "primary key" to "primary index" and "bucket" to "collection".  And remove the ":leveloffset: -1" text at the end of the line (or fix whatever that's supposed to be).

**Comment by mikereiche** [comment]
Note that to use cache.clear() or cache.invalidate(), the keyspace (bucket or collection) must have a primary index.
