### ISSUE TITLE
how to use in @Transactional  annotation?

### ISSUE THREAD

**Issue by moriyahazan** [spring-projects/spring-data-couchbase#1539]
We are using transactions via couchbase-java-sdk now we want move to @Transactional, released as part of Spring Data Couchbase 4.4.2.
Do you have any documentation on how to implement it? 
thanks

**Comment by mikereiche** [comment]
The transactions documentation which will appear in the next release is currently staged at https://mikereiche.github.io/staged/ (look for the Transactions section).

There are all kinds of examples spring-data-couchbase/src/test/java in : git clone git@github.com:spring-projects/spring-data-couchbase.git. (search for test cases with 'Transaction' in the name.

**Comment by mikereiche** [comment]
@transactional is not in 4.4.2.   It is in 5.0.0-M5
