### ISSUE TITLE
TTL issue while using @Document annotation with ReactiveCouchbaseRepository

### ISSUE THREAD

**Issue by balaji-it** [spring-projects/spring-data-couchbase#1549]
TTL issues (document is not getting deleted) while using ReactiveCouchbaseRepository, but it works fine with CouchbaseRepository. TTL is set using @Document annotation like below.

`@Document(expiryExpression = 60, expiryUnit = TimeUnit.SECONDS)`

**Comment by mikereiche** [comment]
> Please open a new Issue with their reproducer.

Please provide everything required to reproduce this. Thanks.

**Comment by mikereiche** [comment]
The ReactiveCouchbaseRepository and CouchbaseRepository use the same code to process the expiration, so it is likely that this is an application error.  All the reactive and non-reactive expiry annotation tests pass.  CouchbaseTemplateKeyValueIntegrationTests.withExpiryAndExpiryAnnotation() and ReactiveCouchbaseTemplateKeyValueIntegrationTests.withExpiryAndExpiryAnnotation().  This case is UserAnnotated.  The repositories rely on the template for processing the annotations.
