### ISSUE TITLE
Performance loss using spring data instead of couchbase SDK

### ISSUE THREAD

**Issue by jjimenezherrera** [spring-projects/spring-data-couchbase#1570]
Hello,

we have detected a performance loss of approximately x8 when writing to couchbase using spring-data-couchbase instead of using the SDK operations.

To reproduce it, we have a large document (a JSON of 566 lines) whose class contains the annotations @Document, @Id, @IdPrefix and several @Field.
Using the following code, we create a list of 1000 documents for insertion through the save method of the CrudRepository interface:

![image](https://user-images.githubusercontent.com/114918934/193561673-a24e5c03-5c63-432f-b363-182c0adde9be.png)

In this way we obtain the times that are seen in the image

![image](https://user-images.githubusercontent.com/114918934/193563545-4bfc02b1-fecd-425e-a8e3-339052dd1dee.png)

However, doing it via SDK using the following code, we obtain the following times:

![image](https://user-images.githubusercontent.com/114918934/193562203-dfb1c84e-5114-4fd9-86ff-cb6a5685bb04.png)
![image](https://user-images.githubusercontent.com/114918934/193562240-5af685b4-0e2b-415f-bf51-83e486bcdf02.png)
![image](https://user-images.githubusercontent.com/114918934/193563588-ee27742f-3d02-4283-b8f4-0f8b6f569303.png)

The values ​​of this test have been obtained on a dockerized environment with 0.5 cores and 1Gb of memory.

What is this performance loss due to? Is there any way to improve that performance so that I don't have to use the SDK directly?

Many thanks

**Comment by mikereiche** [comment]
This seems accurate.  Spring data adds layers of introspection and serialization.  It also processes annotations. It looks like you have a good solution.

**Comment by programmatix** [comment]
In addition, benchmarking on the JVM is notoriously tricky due to JVM warmup.  It'd be worth modifying these tests to use something like the Java Microbenchmark Harness to eliminate this, so you're working with the most accurate figures possible.

**Comment by deniswsrosa** [comment]
If you are inserting documents in a batch like this, apart from using JMH (as mentioned above) to get accurate numbers, I would also recommend you use async on the SDK and reactive repositories on Spring Data.
