### ISSUE TITLE
figure out where reference docs went to in M6.

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1575]
figure out where reference docs went to in M6.

They are present in M5   https://docs.spring.io/spring-data/couchbase/docs/5.0.0-M5/

But missing from M6  https://docs.spring.io/spring-data/couchbase/docs/5.0.0-M6/

This is probably related to adding the spring-data-couchbase root to make  spring-data-couchbase/spring-data-couchbase etc.  https://github.com/spring-projects/spring-data-couchbase/commit/a99825158543bfe1016db58c6f2ad6f55c89840
it looks like the docs used to go in ./target/site/reference/html/ but now they go in ./target/generated-docs/

**Comment by mikereiche** [comment]
@mp911de  - Hi Mark - are the spring-data-couchbase docs expected to go in target/site/reference/html (instead of target/generated-docs) ?   Will undoing that change get them back in  https://docs.spring.io/spring-data/couchbase/docs/... ?

**Comment by mp911de** [comment]
The documentation is being distributed as `spring-data-couchbase-distribute` on the documentation server. This is a consequence of splitting the project into modules. We need to copy over the documentation after each release to the previous path so that it can be exposed.

I did that and the docs for 5.0 M6 are available now.

**Comment by mikereiche** [comment]
Thanks. Should I change the pom(s) to build the documentation under spring-data-couchbase-distribute/target/generated-docs ?

**Comment by mikereiche** [comment]
I can revert it to single-module.
I just thought the multi-module project was the "right" way to do things.

**Comment by mp911de** [comment]
Multi-Module makes only in very specific cases sense. Feel free to go ahead so we can ship that change with next week's release.
