### ISSUE TITLE
Cannot retrieve map that contains BigInteger using SDC.

### ISSUE THREAD

**Issue by mmonti** [spring-projects/spring-data-couchbase#1611]
Hi!

I am running into an issue when i try to retrieve a document that contains a key with a BigInteger type value. 
The error I am getting is a bit missleading since the document is stored correctly but fail to retrieve:

```
java.lang.IllegalArgumentException: Attribute of type java.math.BigInteger cannot be stored and must be converted.
```
This seems to be a limitation only on the SDC sdk since I tried to store and retrieve the document with the Couchbase Driver class (Cluster) and I was able to do it without any issues.
 
I did some debugging in the code and it looks like there is check in the CouchbaseDocument.java class (line 126) that uses CouchbaseSimpleTypes to test if the type of the value that is beign loaded matches certain types: CouchbaseDocument.class, CouchbaseList.class.

```java
 private void verifyValueType(final Object value) {
        if (value != null) {
            Class<?> clazz = value.getClass();
            if (!CouchbaseSimpleTypes.DOCUMENT_TYPES.isSimpleType(clazz)) {
                throw new IllegalArgumentException("Attribute of type " + clazz.getCanonicalName() + " cannot be stored and must be converted.");
            }
        }
    }
```

I created a repository with a couple test to repro the issue: https://github.com/mmonti/sdc-biginteger-issue/blob/master/src/test/java/com/example/biginteger/BigIntegerIssue.java

I am using spring-data-couchbase 4.4.5 in the repro project, but i can confirm that the issue is also present in spring-data-couchbase 3.1.18.

I just wanted to know if this is a known issue and if there is any possible workaround for it. 
Thanks!

**Comment by mikereiche** [comment]
I'll look at your project.
It's not a known issue. There are test cases for BigInteger. And there are BigIntegerToString and StringToBigInteger converters - it should be written as a String and read as String.  If i was written as something other than a String (by something other than SDC), there will be an issue on reading.

It appears you're not using spring-data-couchbase to write it.

>  var savedMap = couchbaseTemplate.getCollection("_default").upsert("1", map);

**Comment by vforchi** [comment]
Are there any news on this issue? I have the same problem, and I don't understand if there is a way forward.

> A better solution would be to add NumberToBigInteger/BigIntegerToNumber converters to OtherConverters - but this would make data written by the "fixed" SDC incompatible for reading with an un-fixed version SDC.

I don't think this is an argument against adding these converters: as long as large numbers in a document can be mapped to BigDecimal/BigInteger, I think SDC should handle them. They could come from any source, not necessarily SDC.

**Comment by mikereiche** [comment]
SDC  serialize/deserialezes  BigIntegers as strings because Integers larger than 2^64 do not fit in longs.  What do you want the behavior to be? Fail on Bigintegers larger than 2^64 ?

**Comment by vforchi** [comment]
I don't understand: is it doing it already or not? Because in your first comment you said this would be a workaround.

**Comment by mikereiche** [comment]
>  I have the same problem

> I don't understand: is it doing it already or not?

What is *it*?  Is it the same as "the same problem"?   If they are the same, and you are still having it - then it is not doing "it".  

Can you be really clear (with examples of the document and the entity class) what you are asking?

**Comment by vforchi** [comment]
I understand your point, but how can I read a document created with another interface, which puts the numbers in as they are? Is there a way to support both formats?

**Comment by mikereiche** [comment]
Including Number as a valid simple type for DOCUMENT_TYPES will result in BigInteger and BigDecimal (and any Number) to be written (and read) in the form of a number (no quotes). I don't know why this was not allowed from the beginning.

CouchbaseSimpleTypes.java: 
```
	public static final SimpleTypeHolder DOCUMENT_TYPES = new SimpleTypeHolder(
			Stream.of(CouchbaseDocument.class, CouchbaseList.class,  Number.class).collect(toSet()), true);
```

Now - there is the issue of BigIntegers and BigDecimals that have already been written as Strings.   Having StringToBigInteger and StringToBigDecimal  \@\ReadingConverters should allow that.
