### ISSUE TITLE
@JsonValue ignored for enums

### ISSUE THREAD

**Issue by thomas-bee** [spring-projects/spring-data-couchbase#1617]
According to the docs of Couchbase's `@JsonValue`: *NOTE: when use for Java enums, one additional feature is that value returned by annotated method is also considered to be the value to deserialize from, not just JSON String to serialize as. This is possible since set of Enum values is constant and it is possible to define mapping, but can not be done in general for POJO types; as such, this is not used for POJO deserialization.*

The following enum should be deserialised / serialised using its `code` property. However, `@JsonValue` has no effect and Springdata Couch tries to **de**serialise by enum name. Note however that using the original Jackson annotation `@JsonValue`, the **de**serialisation does work !
In both cases, serialisation does not work, 

```
public enum ETurbulenceCategory {
    T10("10%"),
    T20("20%"),
    T30("30%");

    private final String code;

    ETurbulenceCategory(String code) {
        this.code = code;
    }
//  DOES WORK FOR DE-SERIALISATION, BUT NOT FOR SERIALSATION
    @com.fasterxml.jackson.annotation.JsonValue
//  DOES NOT WORK AT ALL
//  @com.couchbase.client.core.deps.com.fasterxml.jackson.annotation.JsonValue
    String getCode() {
        return code;
    }
}
```

**Comment by mikereiche** [comment]
spring-data-couchbase does not use the jackson object mapper.  Instead it uses its own MappingCouchbaseConverter. Support for this annotation would need to be added.  

de-serialization using  @com.fasterxml.jackson.annotation.JsonValue did not work when I tested it.


```
Caused by: java.lang.IllegalArgumentException: No enum constant org.springframework.data.couchbase.domain.ETurbulenceCategory.10%
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.springframework.core.convert.support.StringToEnumConverterFactory$StringToEnum.convert(StringToEnumConverterFactory.java:54)
	at org.springframework.core.convert.support.StringToEnumConverterFactory$StringToEnum.convert(StringToEnumConverterFactory.java:39)
	at org.springframework.core.convert.support.GenericConversionService$ConverterFactoryAdapter.convert(GenericConversionService.java:437)
```

**Comment by thomas-bee** [comment]
> spring-data-couchbase does not use the jackson object mapper. Instead it uses its own MappingCouchbaseConverter. Support for this annotation would need to be added.

Thanks a lot @mikereiche 
What, then, is the point of having `@com.couchbase.client.core.deps.com.fasterxml.jackson.annotation.JsonValue` and the documentation that goes with it?

Also, is there a workaround to achieving the intended serialisation / de-serialisation?

**Comment by mikereiche** [comment]
the com.couchbase.client.core.deps.com.fasterxml... classes are just the com.fasterxml... classes repackaged to avoid conflicts when the application may already have com.fasterxml... classes which conflict with the ones needed/used by couchbase.  There is a public method com.couchbase.client.java.codec.JacksonJsonSerializer.preflightCheck() to see if there could be an issue.    I normally recommend just using com.fasterxml... classes unless you run into problems.

I spoke to soon about deserialization not working. It does appear to work.

I can add handling of the annotation to MappingCouchbaseConverter.

**Comment by vforchi** [comment]
I had a similar issue when trying to serialize LocalDate and LocalDateTime.

I still don't understand the purpose of duplicating the jackson (not part of the java SDK) annotations in the spring-data-couchbase module, if they are not used or interpreted. Jackson itself won't work with those annotations, because they are in the wrong package.

I see mainly one problem with implementing serialization/deserialization from scratch: jackson is used in other spring projects (spring-web-mvc, to name one), so if you want to write a simple app that exposes a CRUD API in front of couchbase, and you need some custom mappings, you have to define them twice: once to make the jackson serialization work, needed in the controller, and once to make couchbase work, which seems a bit redundant.

**Comment by mikereiche** [comment]
> I still don't understand the purpose of duplicating the jackson (not part of the java SDK) annotations in the spring-data-couchbase module

They aren't.  They are in the couchbase java sdk module (which is used by the spring-data-couchbase module).

> Jackson itself won't work with those annotations, because they are in the wrong package.

The repackaged jackson annotations will work in the repackaged jackson.

**Comment by mikereiche** [comment]
>  so if you want to write a simple app that exposes a CRUD API in front of couchbase, and you need some custom mappings, you have to define them twice: once to make the jackson serialization work, needed in the controller, and once to make couchbase work, which seems a bit redundant.

Correct. Custom customizations must be defined where they are used. There's really no way around that.  I would love to use the jackson ObjectMapper, but the reason for not relying on the jackson Object Mapper is described in https://github.com/spring-projects/spring-data-couchbase/issues/908.  A good example of having to do two implementations is the Field Level Encryption converter.  The java sdk contains a converter for FLE, and spring-data-couchbase contains a converter for FLE. 

>  needed in the controller, and once to make couchbase work

I'm trying to think of a custom annotation/converter that would need to work in both the controller and couchbase (?). For instance - Field Level Encryption only needs to work for couchbase - everything else can just ignore it.  Something like @JsonValue does need to work in both the controller and spring-data-couchbase, but it's not "custom" (and therefore only needs to be implemented in spring-data-couchbase - which is the purpose of issue #1617).

**Comment by vforchi** [comment]
> Can you open a new issue for that? LocalDate and LocalDateTime should be deserialized without issue (unless they have been serialized to a String by the java sdk )
It was serialized, but to a number, and I wanted a String.

I understand your point, but I still don't see the reason for duplicating the jackson annotation, which I find very confusing.

Besides @JsonValue, @JsonFormat would also be useful. 

Also, I think the documentation could be improved, especially with respect to the mapping.

**Comment by mikereiche** [comment]
> It was serialized, but to a number, and I wanted a String.

As mentioned above - #1203.   I looked at it again yesterday and added a note to it.  Serializing to a String would break non-upgraded spring-data-couchbase applications as they would not have the StringToLocal... converters.

**Comment by mikereiche** [comment]
@vforchi @thomas-bee - this should be available in SNAPSHOT if you want to try it.
