### ISSUE TITLE
QueryCriteria TRUE() to N1QL is behaving differently in version 4.4.5

### ISSUE THREAD

**Issue by amitnimbhorkar** [spring-projects/spring-data-couchbase#1627]
The SpEl query extraction/preparation is behaving wrong after upgrade from **spring-data-couchbase:3.2.6.RELESE** to spring-**data-couchbase:4.4.5**.  The keyword IsTrue/True is expected to be transformed as 'field = TRUE', but it does not. Instead it just adds the field to the query as shown below.

This causes queries perform badly since they don’t pick expected indexes plus possible invalid results.

**Before** : 
Optional<UserDocument> findByIdAndStatusAnd**ActiveDocumentTrue**(String id, String status);

query: SELECT `_class`, `id`, META(`bucket`).`id` AS __id,…. FROM `bucket` WHERE `_class` = "com.blah.UserDocument" AND `id` = $1 and `status` = $2 and **_`activeDocument` = true_**

**After**:
Optional<UserDocument> findByIdAndStatusAnd**ActiveDocumentTrue**(String id, String status);

query: SELECT `_class`, `id`, META(`bucket`).`id` AS __id,…. FROM `bucket` WHERE `_class` = "com.blah.UserDocument" AND `id` = $1 and `status` = $2 and **_`activeDocument`_**

**Comment by mikereiche** [comment]
For the first description ( activeDocument = true ) versus (activeDocument).  Logically, the queries appear to be the same.   To test, I added a property "selectMe" : true to  airline_137 in   travel-sample.inventory.airline and ran the queries below and got the same answer for both.  Can you please provide examples that show the behavior you are describing so I can forward the issue to the query team?  Use "Explain Plan" in the query UI to show the different query plans.

SELECT * from default:`travel-sample`.inventory.airline, default:`travel-sample`.inventory.route where route.airlineid = meta(airline).id  and airline.selectMe = true  

and

SELECT * from default:`travel-sample`.inventory.airline, default:`travel-sample`.inventory.route where route.airlineid = meta(airline).id  and airline.selectMe

**Comment by mikereiche** [comment]
@rt-jar - the query is different yes.  The query that uses META() should be more efficient as META() does not require access to the document data.

**Comment by lbarmako** [comment]
> For the first description ( activeDocument = true ) versus (activeDocument). Logically, the queries are the same. To test, I added a property "selectMe" : true to airline_137 in travel-sample.inventory.airline and ran the queries below and got the same answer for both. Can you please provide examples that show the behavior you are describing so I can forward the issue to the query team? Use "Explain Plan" in the query UI to show the different query plans.
> 
> SELECT * from default:`travel-sample`.inventory.airline, default:`travel-sample`.inventory.route where route.airlineid = meta(airline).id and airline.selectMe = true
> 
> and
> 
> SELECT * from default:`travel-sample`.inventory.airline, default:`travel-sample`.inventory.route where route.airlineid = meta(airline).id and airline.selectMe
> 
**The problem is that it picks a completely different query plan which greatly impacts performance. I realise that it's possible to modify the indexes but why should we have to?! I believe it needs to be fixed and work as described in reference documentation.**

> To get an equality for a boolean value - Remove the 'True' from the method name and change the the method signature to take a boolean argument:
> 
> Optional findByIdAndStatusAndActiveDocument(String id, String status, Boolean isActiveDocument);
> 
> Note to self: This is the implementation of QueryCriteria.TRUE()

**Comment by mikereiche** [comment]
>  I believe it needs to be fixed and work as described in reference documentation

Where can I find this?

**Comment by lbarmako** [comment]
@mikereiche 

Here is a link to the doco: https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.repository.n1ql

It says the following in the table:



IsTrue,True | findByFieldIsTrue | field = TRUE
-- | -- | --
IsFalse,False | findByFieldFalse | field = FALSE

Which release will the fix be in?


****

**Comment by mikereiche** [comment]
Next release - January 13.  5.0.1

**Comment by lbarmako** [comment]
@mikereiche, is it possible to have it in minot 4.4.x release as going to 5.x.x will require a lot more testing that we can't afford at this stage?

**Comment by mikereiche** [comment]
It will also be in 4.4.7 also on January 13.
