### ISSUE TITLE
Never call getAndTouch in ReactiveFindByIdOperationSupport

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1634]
Hello

I'm trying to do a **getAndTouch** in the
https://github.com/spring-projects/spring-data-couchbase/blob/d994eb7bb3cf15f2ede1acc84692316c9f732958/src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java#L88-L90

method and I think there is a bug.
The options are never initialized so the get method is always executed.

Related issue: https://github.com/spring-projects/spring-data-couchbase/pull/1196

Thank you very much

**Comment by mikereiche** [comment]
Can you show the call you are making?

**Comment by jorgerod** [comment]
Hi  @mikereiche 

Sorry I couldn't answer you before, but I've been busy.

As I understand it, to do `getAndTouch` you have to take into account [touchOnRead ](https://docs.spring.io/spring-data/couchbase/docs/current/api/org/springframework/data/couchbase/core/mapping/Document.html#touchOnRead()) property defined in `@Document`

According to the javadoc of the touchOnRead property in org.springframework.data.couchbase.core.mapping.Document:

> An optional flag associated with expiry() indicating whether the expiry timer should be reset whenever the document is directly read (eg. findByOne, findById).

And Spring Data Couchbase is not taking this property into account.

Thank you very much

**Comment by mikereiche** [comment]
Edit:   it seems that relying solely on @Expiry annotation would not work.


"options are never initialized"

It doesn't need to be initialized.  from initGetOptions()

```
	if (expiry != null || options instanceof GetAndTouchOptions) {
		GetAndTouchOptions gOptions = options != null ? (GetAndTouchOptions) options : getAndTouchOptions();
		if (gOptions.build().transcoder() == null) {
			gOptions.transcoder(RawJsonTranscoder.INSTANCE);
		}
		getOptions = gOptions;
```

We can go back and forth with you saying that it doesn't work, and me pointing to the test that shows that it does work.
Do you have any new information?  Can you provide an example of it not working?  

The value comes from expiryToUse() in ReactiveFindByIdOperationSupport.

```
return rc.getAndTouch(id.toString(), expiryToUse(), (GetAndTouchOptions) pArgs.getOptions())
		.flatMap(result -> support.decodeEntity(id, result.contentAs(String.class), result.cas(), domainType,
				pArgs.getScope(), pArgs.getCollection(), null, null));
```

private Duration expiryToUse() {
	Duration expiryToUse = expiry; << from withExpiry()
	if (expiryToUse != null || options instanceof GetAndTouchOptions) {
		if (expiryToUse == null) { // GetAndTouchOptions without specifying expiry -> get expiry from annoation
			final CouchbasePersistentEntity<?> entity = template.getConverter().getMappingContext()
					.getRequiredPersistentEntity(domainType);
			expiryToUse = entity.getExpiryDuration();
		}
	}
	return expiryToUse;
}
