### ISSUE TITLE
v2.7.3 - save() not working as expected for updates 

### ISSUE THREAD

**Issue by sagarikamraj** [spring-projects/spring-data-couchbase#1658]
I have recently upgraded my project to java 17 and spring boot 2.7.4 and spring cloud 2021.0.4. I am using mavenBom for spring cloud dependency management. It has brought in spring-data-commons-2.7.3.

With the upgrade, the CRUD repository's save() doesn't seem to be updating the existing objects. I am getting a duplicate key exception. (`org.springframework.dao.DuplicateKeyException: Document with the given id already exists`). I have already tried enabling transaction management, but to no avail.

Could you please help.

**Comment by mp911de** [comment]
Moved into Spring Data Couchbase as the ticket relates to Couchbase and not Spring Data Commons.

**Comment by sagarikamraj** [comment]
spring-data-couchbase version that I am using is 4.4.3

**Comment by mikereiche** [comment]
DuplicateKey can occur on insert().  If your entity object has an @Version property that is zero, insert() will be used.   This is the correct/normal behavior.
If you want to use upsert() on an entiy class that has an @Version property, you'll need to explicitly use template.upsertById() or introduce your own repository.upsert() method.  Or override the repository.save() method.

**Comment by mikereiche** [comment]
see https://github.com/spring-projects/spring-data-couchbase/issues/1277

**Comment by sagarikamraj** [comment]
@mikereiche , thanks for confirming that it needs an explicit overriding of repository methods for accommodating upsert operations. 
Could you please share a sample of the update query that I could use.  It is a big data object, I am checking if there is any alternative to updating field by field on a typical SQL update query.

Example of the typical query I am referring to: 
```
update MyBucket 
set departureTime = 'some', 
and scheduleId = 
and dataVersion = 
and orders = 
and returnTime = 
and waveId = 
and vehicleType = 
and friendlyId = 
and planStatus = 
and dateTime = 
where id = 'a16555d6-0ac1-4a15-9d6c-1b9edb5825e5';
```

**Comment by mikereiche** [comment]
>  replace almost the entire object (maintaining only the ID )? Kind of an equivalent to template.replaceById()

How about template.upsertById() ?
