### ISSUE TITLE
Support of the Sub-Document operations

### ISSUE THREAD

**Issue by babltiga** [spring-projects/spring-data-couchbase#1659]
Are there any plans to support the [Sub-Document ](https://docs.couchbase.com/java-sdk/current/howtos/subdocument-operations.html)operations? In most of cases, the updates on the documents are partial so users can benefit from using Sub-Document mutations. 

So something like this can be achieved without using Collections directly.

```java
@Repository
public interface AirlineRepository extends CouchbaseRepository<Airline, String> {
	@MutateOnly({"name"})
	void upsert(Airline airline);

}
```
which is equivalent of

```java
couchbaseTemplate.getCollection("airline")
     .mutateIn(airline.getId(), Collections.singletonList(upsert("name", airline.getName())));
```

**Comment by mikereiche** [comment]
Subdocument support is a  known outage, but this is the first request for it.  In #1310, @jorgerod said he had  "The operations that I have added are, for example, the saving with the possibility of the insertById, operations to work the api of subdocuments", but hasn't shared that.

**Comment by babltiga** [comment]
I'm ready to work on this if we of course agree on the API )

**Comment by mikereiche** [comment]
Let's see - the possibilities for subdocuments is https://docs.couchbase.com/java-sdk/current/howtos/subdocument-operations.html.   Let's ignore the counter and binary (append, prepend), and array append/prepend functions for now.

For new stuff, we usually first put it in the template, and then figure out how to call it from the repository.

For the template: findById().project( String[] propertyNames ) already uses the subdocument api lookUpIn (indirectly, through the java sdk get() method).   It might make sense to add similar methods - insert(),  upsert(), replace() and remove() methods to upsertById() and replaceById().  (an alternative would be to create a new mutateById() operation - 

insert() can go on either replaceById() or upsertById(), the specified field must not exist:

template.replaceById(Airline.class).insert({"name", "address"}).one(someAirline) // replaceById does CAS

template.upsertById(Airline.class).insert({"name", "address"}).one(someAirline) // upsertById does not do CAS

replace() can go on either replaceById() or upsertById(), the specified field must exist :

template.replaceById(Airline.class).replace({"name", "address"}).one(someAirline) // replaceById does CAS

template.upsertById(Airline.class).replace({"name", "address"}).one(someAirline) // upsertById does not do CAS

upsert() can go on either replaceById() or upsertById()

template.replaceById(Airline.class).upsert({"name", "address"}).one(someAirline) // replaceById does CAS

template.upsertById(Airline.class).upsert({"name", "address"}).one(someAirline) // upsertById does not do CAS

remove() needs only the id - it doesn't need the object for values - it is just remove properties. If it has the object it can do CAS.

template.replaceById(Airline.class).remove({"name", "address"}).one(someAirline) // replaceById does CAS, needs airline object

template.upsertById(Airline.class).remove({"name", "address"}).one(id) // upsertById does not do CAS, does not need airline object

When that is available in the template, then it can be called in a repository method :

  public void upsert(T airline, String[] propertyPaths){
      template.upsertById(T).upsert(propertyPaths).one(airline);
  }
