### ISSUE TITLE
 ReactiveCouchbaseTemplateKeyValueIntegrationTests.findByIdWithLock  needs longer duration

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1662]
The two second duration results in the test failing occasionally.  (KV timeout is 2.5 seconds).

**Comment by babltiga** [comment]
It seems introduced with my test case, let me try to fix this one ...

**Comment by babltiga** [comment]
Does it fail on data retrieval or on data cleanup? Sadly Jenkins is not publicly accessible for me to see the logs ...

**Comment by mikereiche** [comment]
Sadly, the integration tests are not ran by jenkins as they need a cb server, and right now the runs in jenkings run without a cb server.

To run theses tests, it's necessary to modify the src/test/resources to point to a running cb server ( change the type=mocked to type=unmanaged and set the username/password and connection string to the cb server, then mvn integration-test)

All that it needs is the two second duration increased to 5 seconds or so.

**Comment by mikereiche** [comment]
fixed along with  #1663
