### ISSUE TITLE
[question] Set versions of tracing-opentelemetry, Metrics-OpenTelemetry or Metrics-Micrometer 

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1702]
Hello

I have a question/suggestion. 

In my project, we use **com.couchbase.client:tracing-opentelemetry** and this dependency is brought transitively **com.couchbase.client:core-io**.
**com.couchbase.client:java-client** is also transitively fetched **com.couchbase.client:core-io**  and the version is set by spring-boot-dependencies. 

Therefore, at each spring-boot version upgrade, the version of **com.couchbase.client:java-client** is automatically upgraded but not the version of **com.couchbase.client:tracing-opentelemetry** and sometimes the version of **com.couchbase.client:core-io** is not compatible. 

Does it make sense to set the version of tracing-opentelemetry, Metrics-OpenTelemetry or Metrics-Micrometer in spring-data-couchbase, what do you think?

Thank you very much

**Comment by mikereiche** [comment]
I don't think it is possible for a property set in the java-client pom.xml to be visible outside of anything where java-client is not a parent.

**Comment by jorgerod** [comment]
You are right.
Maybe a bom in java-client would be nice.
I'm going to tell him about it.

**Comment by mikereiche** [comment]
couchbase-jvm-clients is the uber artifact that has dependencies for both java-client and the couchbase telemetry artifacts.  But spring-data-couchbase has a dependency on only java-client (to keep it as light-weight as possible).

**Comment by mikereiche** [comment]
I'm looking at the "Adding a BOM as a Dependency" example in https://reflectoring.io/maven-bom/

A version still needs to be specified in the dependencyManagement section - so I don't see how that improves the situation.
