### ISSUE TITLE
Test against Java 20 in CI.

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-couchbase#1703]

**Comment by mikereiche** [comment]
Tests run without errors on

/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

```
[INFO] Results:
[INFO] 
[WARNING] Tests run: 518, Failures: 0, Errors: 0, Skipped: 11
```
