### ISSUE TITLE
Using CoucbaseRepository.delete() causes @Transactional methods to error

### ISSUE THREAD

**Issue by sf-eng** [spring-projects/spring-data-couchbase#1725]
I'm using spring-data-couchbase 5.0.5 with spring boot 3.0.6.  

When attempting to execute a service method marked @Transactional which uses a CouchbaseRepository.delete call, the transaction fails with the error:
"cas must be supplied for tx remove".

I think I tracked this down to the SimpleCouchbaseRepository class's delete() implementation not supplying the .withCas() method.
To work around this I've implemented my own custom repository extension with a void deleteTx(T entity) which does employ the .withCas() method.

Is there a better supported way to use repository delete methods in @Transactional blocks?

**Comment by mikereiche** [comment]
See https://github.com/spring-projects/spring-data-couchbase/issues/1688
It's fixed in 5.0.5

**Comment by mikereiche** [comment]
It's fixed in template.deleteByid(..).oneEntity(entity) - you can use that.  I'll fix it in the repository, it will be in the 5.0.6 release on May 12.

> Is there a better supported way to use repository delete methods in @transactional blocks?

Can also used lambdas...
Section 9.5 https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.transactions
