### ISSUE TITLE
#n1ql.bucket returns the collection in v5

### ISSUE THREAD

**Issue by babltiga** [spring-projects/spring-data-couchbase#1799]
Based on the answers from https://github.com/spring-projects/spring-data-couchbase/issues/1536 and https://github.com/spring-projects/spring-data-couchbase/issues/1445 it seems that the `#n1ql.bucket` should always return bucket name starting from version 5, but still even in the latest versions, it returns the collection name.

I'm asking about this line https://github.com/spring-projects/spring-data-couchbase/blob/f41d4b94e07923fec2f75ce71c51ea7f376112d0/src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java#L169C30-L169C30 

Should this be fixed? Or was the change postponed for the next major version?

**Comment by mikereiche** [comment]
in https://github.com/spring-projects/spring-data-couchbase/issues/1445 , there is a note about backing out the change - which was done in  #1463 - but that was supposed to be only on 4.4.x.  I'm trying to figure out how that got in 5.x - or even if the original change was done to 5.x.

```
see https://github.com/spring-projects/spring-data-couchbase/issues/1445. n1ql.bucket should remain as

b = collection != null ? collection : bucket
```

**Comment by babltiga** [comment]
OK, if you think it should be changed, I'm ready to create a PR )

**Comment by mikereiche** [comment]
Yes. Submit the PR and I'll approve it.   It will change the behavior mid-version, but it's a bug-fix   Be sure to also fix the test case I indicated.  

I'm not sure if you're already running the integration tests against a live server, but to do that edit src/test/resources/integration.properties to point to a real server before running mvn integration-test
