### ISSUE TITLE
Unexpected decode exception when using `RawJsonTranscoder.INSTANCE` with caching

### ISSUE THREAD

**Issue by rm-hull** [spring-projects/spring-data-couchbase#1814]
Using a `RawJsonTranscoder.INSTANCE` as my json transcoder, and populating a string value yields the following exception on decode:

```
com.couchbase.client.core.error.DecodingFailureException: RawJsonTranscoder can only decode into either byte[] or String!
	at com.couchbase.client.java.codec.RawJsonTranscoder.decode(RawJsonTranscoder.java:56)
	at com.couchbase.client.java.kv.GetResult.contentAs(GetResult.java:155)
	at org.springframework.data.couchbase.cache.DefaultCouchbaseCacheWriter.get(DefaultCouchbaseCacheWriter.java:90)
	at org.springframework.data.couchbase.cache.DefaultCouchbaseCacheWriter.putIfAbsent(DefaultCouchbaseCacheWriter.java:82)
	at org.springframework.data.couchbase.cache.CouchbaseCache.putIfAbsent(CouchbaseCache.java:119)
        --- 8< --- snipped --- 8< ---
```

I guess this would never work, since it is trying to [get the content as an object](https://github.com/spring-projects/spring-data-couchbase/blob/6f5efea114407be0bbf7f3c98cc5c66c3d5b1469/src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java#L90), but that is not supported by the raw encoder.

Is that by design (and I just shouldn't use a raw json transcoder), or this an oversight / bug?

cc: @AmyRob27

**Comment by mikereiche** [comment]
why are you going out of your way to use a transcoder that doesn't work for your case?

**Comment by rm-hull** [comment]
Well, we're not using it anymore.

The default one appeared to be a binary transcoder which we didn't want hence setting the raw one.

The docs suggest that it should default to the regular Jackson serialiser and JSON transcoder but that is definitely not what we saw (however, I'm open to the suggestion that it may be how we configured the cache manager).

My main points were:
* why provide a transcoder that can't be used (admittedly we are attempting to use it via the caching framework).
" there is no mention of the limitations of the raw transcoder in the docs.

These are the docs I'm referring to: https://docs.couchbase.com/java-sdk/current/howtos/transcoders-nonjson.html

**Comment by mikereiche** [comment]
> The default one appeared to be a binary transcoder which we didn't want hence setting the raw one.

The default transcoder is the JsonTranscoder. It is the default transcoder from the ClusterEnvironment.  To get some other Transcoder, you either have to specify it in the options of the 'get' call (or template method) or in the ClusterEnvironment.   If you provide you're app, I'lll figure out where it is being set. 

`    this.transcoder = defaultIfNull(builder.transcoder, () -> JsonTranscoder.create(jsonSerializer));
`     
    > why provide a transcoder that can't be used (admittedly we are attempting to use it via the caching framework).

It can't be used for your case.  It can be used for other cases.

**Comment by mikereiche** [comment]
The defaultCacheConfig uses SerializableTranscoder.  Perhaps you are creating your own ConcuchbaseCacheConfiguration with some other transcoder.

		return new CouchbaseCacheConfiguration(Duration.ZERO, true, true, CacheKeyPrefix.simple(), conversionService,	SerializableTranscoder.INSTANCE, null);

**Comment by mikereiche** [comment]
> but this would never work because the [DefaultCouchbaseCacheWriter#get()](https://github.com/spring-projects/spring-data-couchbase/blob/6f5efea114407be0bbf7f3c98cc5c66c3d5b1469/src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java#L90) method calls .contentAs(Object.class)

Hmm... String is an Object, even if the RawJsonTranscoder disagrees.  But given the class of Object.class, I don't know RawJsonTranscoder would know it should use String.class.   And from the other side -  I don't know how get() would know it should use String.class (or anything more specific than Object.class - SerializableTranscoder is fine with Object.class because the class is identified in the serialized data).
