### ISSUE TITLE
"IN" clause bug in spring-data-couchbase-5.1.0

### ISSUE THREAD

**Issue by kutayyaman** [spring-projects/spring-data-couchbase#1820]
Hi, when we try to use `IN` clause with template method as seen below in spring-data-couchbase-5.1.0
`List<DispatcherResult> findByCargoProviderIdIn(List<Integer> cargoProviders);`
We are passing Integer list here but its converting this integer values to String as we see in the query options log. This integer value is cast to string as "10".
`query options: {"args":[["10"]],"client_context_id":"50698bad-b0ab-44db-9d03-9af1ff4ba2fe","metrics":false}`
Because of this casting our query returning 0 rows although we have some rows which cargoProvider value is equals to 10

I think it is a bug and to solve this problem for now, we used the @Query annotation as below
`@Query("#{#n1ql.selectEntity} WHERE cargoProviderId IN $1 AND #{#n1ql.filter}")
    List<DispatcherResult> findByCargoProviderIdIn(List<Integer> cargoProviders);`
And now we can see this 10 is stay as Integer in query options like this:
`query options: {"args":[[10]],"client_context_id":"123bb2ad-bdd2-44d8-869c-ffece1e9cd82","metrics":false}`

I hope I was able to explain the problem, thank you all

**Comment by mikereiche** [comment]
Can you post your code?  I get:

```
Integer[] cargoProviders={1,2,3};
List<Airport> as = airportRepository.getAllByIataNot(cargoProviders);
			
2023-09-13 18:10:02,335 DEBUG data.couchbase.core.query.OptionsBuilder: 106 - query options: {"args":[[1,2,3]],"client_context_id":"be5cb414-2aa3-4e85-ac67-b1ff4093d20e","metrics":false}
```

**Comment by kutayyaman** [comment]
Thank you for answer and i update my version to 5.1.3 and its fixed. 
I think there is a bug in 5.1.0 but there is no fix release note about this.
Thank you for support again
