### ISSUE TITLE
ExecutableFindByQueryOperationSupport.withConsistency is returning a deprecated interface

### ISSUE THREAD

**Issue by yaronyudov** [spring-projects/spring-data-couchbase#1851]
While switching implementation from FindByQueryConsistentWith.consistentWith to FindByQueryWithConsistency.withConsistency
I noticed that the return interface is the deprecated one (I mentioned above)

![image](https://github.com/spring-projects/spring-data-couchbase/assets/21036951/c728aade-3220-463c-b27c-867b39f9166c)

**Comment by mikereiche** [comment]
> While switching implementation from FindByQueryConsistentWith.consistentWith to FindByQueryWithConsistency.withConsistency

Why?

**Comment by yaronyudov** [comment]
My point is - that it "feels" weird that the new method to be used instead of the deprecated one - will eventually return the deprecated one...
In case this is intentional - is there any different suggestion as to what should be used instead of the deprecated 'consistentWith'? 
(Just trying to ensure no additional work will be required on a "dealt with" code in the next version)

**Comment by mikereiche** [comment]
> it "feels" weird that the new method to be used instead of the deprecated one

I don't know what you want.  The new method has the correct name and the correct implementation.   The old method has the wrong name but the correct implementation - as the comment indicates, the only thing wrong with it is the name (it is not consistent with the other fluent methods with care all with*something*().    Do you want the new method to use something other than the correct implementation?
