### ISSUE TITLE
Spring boot: 3.2.0, Spring data Couchbase: 5.2.0: java.lang.IllegalArgumentException: Attribute of type java.util.Collections.SingletonList cannot be stored and must be converted.

### ISSUE THREAD

**Issue by ilangranet** [spring-projects/spring-data-couchbase#1875]
Hi,

I am using Spring boot: 3.2.0 with Spring data Couchbase: 5.2.0

I have an entity defined with a field of type Object (this field can be everything (String or List...)):

```
public class Person {
    @NotNull
    @Id
    private String id;

    @NotNull
    @Field
    private String name;

    @Field
    private int age;

    @Field
    private Object myObject;
}
```
while trying to save it using this:
`personRepository.save(new Person("1", "Alice", 25, Collections.singletonList("my issue")));`

It failed on java.lang.IllegalArgumentException: Attribute of type java.util.Collections.SingletonList cannot be stored and must be converted.

it was working with previous version: Spring boot: 2.7.13, Spring data Couchbase: 4.4.13.
[demo.zip](https://github.com/spring-projects/spring-data-couchbase/files/13628870/demo.zip)

Find attached the project where it failed: to reproduce, run PersonRepositoryTest

Any suggestion?

Thank you

**Comment by mikereiche** [comment]
This should work and I'll fix it. In the meantime,  you might try a JsonArray instead of a List

**Comment by ilangranet** [comment]
I got the same
java.lang.IllegalArgumentException: Attribute of type com.couchbase.client.java.json.JsonArray cannot be stored and must be converted.

**Comment by ilangranet** [comment]
> This should work and I'll fix it. In the meantime, you might try a JsonArray instead of a List

java.lang.IllegalArgumentException: Attribute of type com.couchbase.client.java.json.JsonArray cannot be stored and must be converted.

**Comment by mikereiche** [comment]
I haven't investigated this yet, but this is more likely the issue.  How is Object supposed to be serialized? Deserialized? What constructor should be used?

    @Field
    private Object myObject;

**Comment by roman-sinyakov** [comment]
@mikereiche this is a regression in v5. Could you make it work like it used to be in v4 ?

**Comment by mikereiche** [comment]
The issue  is that conversion.isSimpleType() considers Object to be a simple type, while the 

[MappingCouchbaseConverter
](https://github.com/spring-projects/spring-data-couchbase/blob/9b292aedb7719747b1d3c1e659a498b595a5c88b/src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java#L617)
```
					if (!conversions.isSimpleType(prop.getType())) {
						writePropertyInternal(propertyObj, target, prop, accessor);
					} else {
						writeSimpleInternal(prop, accessor, target, prop.getFieldName());
					}
```

While verifyValue (called from target.put() called from writeSimpleInternal()) does not consider it to be a simpletype.  https://github.com/spring-projects/spring-data-couchbase/blob/9b292aedb7719747b1d3c1e659a498b595a5c88b/src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseDocument.java#L270

```
	private void verifyValueType(final Object value) {
		if (value == null) {
			return;
		}
		final Class<?> clazz = value.getClass();
		if (CouchbaseSimpleTypes.DOCUMENT_TYPES.isSimpleType(clazz)) {
			return;
		}
		throw new IllegalArgumentException(
				"Attribute of type " + clazz.getCanonicalName() + " cannot be stored and must be converted.");
	}
```

**Comment by mikereiche** [comment]
@roman-sinyakov 
> this is a regression in v5. Could you make it work like it used to be in v4 ?

I can make the serialization (save) work.  But it appears that the deserialization (findById etc), did not work in v4 and won't work in v5 without other changes.

**Comment by mikereiche** [comment]
@roman-sinyakov @ilangranet - are you ok with saving working, but reading (still) not working?

**Comment by ilangranet** [comment]
> @roman-sinyakov @ilangranet - are you ok with saving working, but reading (still) not working?

with spring data 4.x, save and read were working.
we still need both.

**Comment by mikereiche** [comment]
I thought I tried reading with 4.x and it didn't work. I'll look again

**Comment by ilangranet** [comment]
> I tried with spring boot 2.7.13, which brings 
<dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-couchbase</artifactId>
      <version>4.4.13</version>
      <scope>compile</scope>
</dependency>
[PersonRepositoryTest.java.zip](https://github.com/spring-projects/spring-data-couchbase/files/13696726/PersonRepositoryTest.java.zip)

it worked both save and read.

**Comment by mikereiche** [comment]
Thanks. I'll investigate on Monday.

**Comment by mikereiche** [comment]
@ilangranet - I can't get the read to work in 4.4.x or in anything else.  Since the field type is Object, it doesn't have a componentType (line 766).
So when readCollection() is called at line 776 with componentType==null, it throws an exception because it does not accept a null targetType. 

https://github.com/spring-projects/spring-data-couchbase/blob/061f7ab8ed530ecd9337b7d56bfcabba194729f6/src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java#L755:L783

**Comment by korkutkose** [comment]
@mikereiche Hi, I've just run across to this issue on starter-data-couchbase 3.2.2 with data-couchbase 5.2.2. 
I see that this has been merged to 5.2.x and main branch already.
When will it be shipped, any plans? 
Any workarounds you'd suggest until that time rather than rolling back?
Thanks.

**Comment by mikereiche** [comment]
Tomorrow. https://calendar.spring.io/

**Comment by umeshmishra099** [comment]
Hi, 
We getting same issue with starter-data-couchbase 3.4.3 with data-couchbase 5.4.3

**Comment by umeshmishra099** [comment]
it was working Spring boot: [3.2.4]
[demo_3_2.zip](https://github.com/user-attachments/files/19492796/demo_3_2.zip)
it fails with Spring boot: [3.4.3]
[demo_3_4.zip](https://github.com/user-attachments/files/19492800/demo_3_4.zip)

Step to test 
1) Run spring boot application
2) Run this curl
curl --location --request POST 'http://localhost:8080/api/testpojo/create' \
--header 'Content-Type: application/json' \
--data-raw '{
	"field1": "value55",
	"field2": [{
		"locale": "en-US",
		"value": "test data11"
	}],
	"field3": "value3",
	"field4": "value4",
	"field5": "value5"
}'
3) it fails for spring boot 3.4.3 with error j**ava.lang.IllegalArgumentException: Attribute of type java.util.ArrayList cannot be stored and must be converted.**
