### ISSUE TITLE
Make CrudMethodMetadataPostProcessor public and make factory  getTargetRepository() not final (so factory can be extended)

### ISSUE THREAD

**Issue by mikereiche** [spring-projects/spring-data-couchbase#1877]
From #1873

For the custom repository - I don't know why the factory getTargetRepository() method is final. If it wasn't, you could just extend the existing couchbase factory. Similarily with the CrudMethodMetadataPostProcessor - if it was public, you could just use it instead of redefining it. Those two things can be changed to make your implementation a little easier.

**Comment by bipoool** [comment]
Can I work on this @mikereiche ?

**Comment by bipoool** [comment]
@mikereiche ?
