### ISSUE TITLE
Set document expiration dynamically

### ISSUE THREAD

**Issue by jorgerod** [spring-projects/spring-data-couchbase#1898]
Hi

We have a use case in which depending on some conditions, the expiration time of a document is variable, therefore, every time I save the document previously I have to dynamically calculate that expiration time.

For that case, as far as I have seen, at repository level, there is no option.

At the template level, I could do it by overwriting the save method and adding _withExpiry_ when necessary (in fact, this method is defined but not used in the template.)

 
I think it would be interesting to add the feature at the repository level to make it easier to use. 

How do you see it?

**Comment by mikereiche** [comment]
> We have a use case in which depending on some conditions, the expiration time of a document is variable, therefore, every time I save the document previously I have to dynamically calculate that expiration time.

I'm not sure if you want to (a) set the document to expire at a different time every time it is updated; or (b)  just to keep the same expiration time even when the document is updated [the sdk has a keepExpiry for this]; or (c) just set expiration times of different documents to different values.  I think it is (c). Is that correct?

> At the template level, I could do it by overwriting the save method and adding withExpiry when necessary (in fact, this method is defined but not used in the template.)

I'm not sure why you state "but not used in the template".  It can be used if the application chooses to use it. (it is not used by the repository, as there is no api). 

> I think it would be interesting to add the feature at the repository level to make it easier to use.

This is such a good idea that it is already implemented.  Make your repository interface extend 

```
@Repository
public interface AirlineRepository extends CouchbaseRepository<Airline, String>, DynamicProxyable<AirlineRepository> {..}
```

Then an Options for the Couchbase SDK can be set with :

insertWithOptionsRepository = airlineRepository.withOptions(InsertOptions.InsertOptions().withExpiry(....))
insertWithOptionsRepository.save(myAirline);

There is a little trickery here that repository.save() will sometimes use insert, sometimes upsert, and sometimes replace and the caller must determine which is going to be used and make the withOptions() argument match. 

```
org.springframework.data.couchbase.repository.CouchbaseRepositoryQueryIntegrationTests

@Test
public void testExpiration() {
	Airport airport = new Airport("1", "iata21", "icao21");
	airportRepository.withOptions(InsertOptions.insertOptions().expiry(Duration.ofSeconds(10))).save(airport);
	Airport foundAirport = airportRepository.findByIata(airport.getIata());
	assertNotEquals(0, foundAirport.getExpiration());
	airportRepository.delete(airport);
}
```

**Comment by jorgerod** [comment]
Hi @mikereiche 

I didn't know _DynamicProxyable_. Checking in detail, I don't think it is quite correct.

At the spring-data-couchbase user level, I don't think it would be intuitive or user friendly to have to know if the operation will be insert, replace or upsert. It is logic that spring-data-couchbase abstracts using the save method. 
I think it would be bringing couchbase-sdk concepts to the spring-data-couchbase layer.

I don't know if this could be done in a more user-friendly way.

In the meantime, I have added this [issue to the couchbase sdk ](https://issues.couchbase.com/browse/JCBC-2121) so that _InsertOptions.java, ReplaceOptions.java and UpsertOptions.java_ extend from a new class and have the common properties.



How do you see it?

**Comment by mikereiche** [comment]
" I don't think it would be intuitive or user friendly to have to know if the operation will be insert, replace or upsert."

You can write a wrapper for save() that has the same logic as save() to produce the required xxxxOptions object.   If you want to make that totally invisible, you could put it in the handler in DynamicProxyable.  If it has an 'options', and save() is called, then create the correct type of options object.

Spring Data Repository methods don't have implementation-specific parameters.

**Comment by mikereiche** [comment]
I'm going to close this. If there are more question, please reopen.
