### ISSUE TITLE
Remove Querydsl and `com.couchbase` split packages

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-couchbase#1906]
These are discouraged as of Java 9++ and all tooling around modules starts falling apart.

**Comment by mikereiche** [comment]
Hi @mp911de  - I'd be happy to do this - could you outline what is needed for this? Thanks.

**Comment by mp911de** [comment]
For the com.couchbase package, the constructor of ReactiveTransactionAttemptContext must be made public (in the driver).

I’m not sure why the querydsl package is there, if querydsl hosts already couchbase code, it would be good to merge the code from spring data back into querydsl.
Am 20. Feb. 2024, 18:13 +0100 schrieb Michael Reiche ***@***.***>:
