### ISSUE TITLE
How to set the different config for different environments while using AbstractCouchbaseConfiguration

### ISSUE THREAD

**Issue by hooverhe** [spring-projects/spring-data-couchbase#1907]
**Title: How to set the different config for different environments while using AbstractCouchbaseConfiguration, can you give me one example?

I am using:
Couchbase Server: 7.2.4
spring-boot-starter-parent: 2.7.9
spring-data-couchbase: 4.4.8 in the dependency: spring-boot-starter-data-couchbase**

https://docs.spring.io/spring-data/couchbase/reference/couchbase/configuration.html

Annotation-based Configuration ("JavaConfig")
To get started, all you need to do is subclass the AbstractCouchbaseConfiguration and implement the abstract methods.

Example 5. Extending the AbstractCouchbaseConfiguration
@Configuration
public class Config extends AbstractCouchbaseConfiguration {

    @Override
    public String getConnectionString() {
        return "couchbase://127.0.0.1";
    }

    @Override
    public String getUserName() {
        return "Administrator";
    }

    @Override
    public String getPassword() {
        return "password";
    }

    @Override
    public String getBucketName() {
        return "travel-sample";
    }
}

![image](https://github.com/spring-projects/spring-data-couchbase/assets/20389331/dd82a7fb-779e-4a27-8c18-97f59b8a5614)

**Comment by mikereiche** [comment]
There are many different ways to get configuration information in spring.   https://spring.io/blog/2020/04/23/spring-tips-configuration

**Comment by mikereiche** [comment]
Closing as there are no follow-up comments.
