### ISSUE TITLE
Bug: Regression - Spring Boot 3.2.3 app fails to compile with Spring Data Couchbase

### ISSUE THREAD

**Issue by juliojgd** [spring-projects/spring-data-couchbase#1909]
We come from https://github.com/spring-projects/spring-boot/issues/39740#issuecomment-1961240086

You can find the reproducer in the aforementioned issue, but it's trivial. If you simply add Spring Data Couchbase starter to Spring Boot 3.2.3 simplest application, it fails to compile (Maven builds).

Maybe also related with:
- https://github.com/spring-projects/spring-data-couchbase/commit/86713c527c0e6cf5a3fde6fa44f119cc719c9bb9
- https://github.com/spring-projects/spring-data-couchbase/issues/1906

**Comment by christophstrobl** [comment]
@mikereiche fix seems to have been only applied to the _main_ branch, so we're sill seeing the issue with current `5.2.4-SNAPSHOT`.
