### ISSUE TITLE
findAll() should work out of the box. [DATACOUCH-33]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#348]
**[Pavel Bernshtam](https://jira.spring.io/secure/ViewProfile.jspa?name=javax)** opened **[DATACOUCH-33](https://jira.spring.io/browse/DATACOUCH-33?redirect=false)** and commented

In order to make repository.findAll working you need create a view with name
_design/dev_YOUR_CLASS_NAME/all
and map function
function (doc, meta) {
emit(meta.id, doc);
}

findAll() should work w/o any additional work

---

**Issue Links:**
- [DATACOUCH-85](https://jira.spring.io/browse/DATACOUCH-85) Creating view by hand should not be needed
 (_**"is duplicated by"**_)

2 votes, 6 watchers

**Comment by mikereiche** [comment]
This issue no longer exists.

**Comment by mp911de** [comment]
@mikereiche You can add a declined or invalid label to issues that do no longer apply. That way, we can count how many tickets were rejected or invalid in a later reporting over tickets.
