### ISSUE TITLE
Add XML Config support for the mapping converter [DATACOUCH-83]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#394]
**[Michael Nitschinger](https://jira.spring.io/secure/ViewProfile.jspa?name=daschl)** opened **[DATACOUCH-83](https://jira.spring.io/browse/DATACOUCH-83?redirect=false)** and commented

---
No further details from [DATACOUCH-83](https://jira.spring.io/browse/DATACOUCH-83?redirect=false)

**Comment by mikereiche** [comment]
no longer doing xml config support.
