### ISSUE TITLE
Improve handling of hierarchy of classes [DATACOUCH-217]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#527]
**[Simon Baslé](https://jira.spring.io/secure/ViewProfile.jspa?name=simonbasle)** opened **[DATACOUCH-217](https://jira.spring.io/browse/DATACOUCH-217?redirect=false)** and commented

As per discussion with Oliver:

Look into `TypeMapper`. `MongoTypeMapper` has an extension to collate several concrete types of a class hierarchy and recognize them in a repository of the top parent class.
Currently we sort of expect the type expansion to happen on the query side of things.
So if you queried for the abstract type you'd basically return this into an "in (all known concrete type)" criteria for the query.
Which keeps the complexity in the query and doesn't pollute the database that much

---

**Affects:** 2.1 M1 (Hopper)

1 votes, 2 watchers

**Comment by mikereiche** [comment]
> So if you queried for the abstract type you'd basically return this into an "in (all known concrete type)" criteria for the query.

I think couchbase does this.  The repository (or domain class) can be an Abstract type and will be deserialized into the _class from which it was persisted.
