### ISSUE TITLE
Allows tuning of CustomConversions through a builder bean [DATACOUCH-230]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#541]
**[Simon Baslé](https://jira.spring.io/secure/ViewProfile.jspa?name=simonbasle)** opened **[DATACOUCH-230](https://jira.spring.io/browse/DATACOUCH-230?redirect=false)** and commented

---
No further details from [DATACOUCH-230](https://jira.spring.io/browse/DATACOUCH-230?redirect=false)

**Comment by mikereiche** [comment]
It has a CouchbaseConverterConfigurationAdapter for customization.

The method AbstractCouchbaseConfiguration can be overriden.

public CustomConversions customConversions(CryptoManager cryptoManager, ObjectMapper objectMapper) {
