### ISSUE TITLE
findAll using N1QL is faster  [DATACOUCH-233]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#545]
**[Ali Shahbour](https://jira.spring.io/secure/ViewProfile.jspa?name=shahbour)** opened **[DATACOUCH-233](https://jira.spring.io/browse/DATACOUCH-233?redirect=false)** and commented

When trying to use findAll backed up by view it would take around 10 second to retrieve 327 document out of 900 document the total size of bucket , while if i used another N1QL query to get all the documents i got them in fraction of second .

```java
public interface CountryRepository extends CrudRepository<Country, String> {
    @Query("#{#n1ql.selectEntity} WHERE #{#n1ql.filter}")
    List<Country> findAllCountries();
}
```

what i noticed is that when using N1QL i got all the document at once ops went up to 250 while when using view it stay between 6 and 8 for around 10 second .

I think N1QL should be the default backend for all queries including findAll

---

**Reference URL:** http://stackoverflow.com/questions/37560663/spring-data-couchbase-findall-speed/37649932#37649932

**Issue Links:**
- [DATACOUCH-228](https://jira.spring.io/browse/DATACOUCH-228) findByView could be made more performant by using async API internally

**Comment by mikereiche** [comment]
Views are deprecated.
