### ISSUE TITLE
Add more default converters [DATACOUCH-234]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#546]
**[Simon Baslé](https://jira.spring.io/secure/ViewProfile.jspa?name=simonbasle)** opened **[DATACOUCH-234](https://jira.spring.io/browse/DATACOUCH-234?redirect=false)** and commented

For instance, there is no `BigInteger` default converter, and serialization fails for these.

Take inspiration from [MongoConverters](http://example.com)https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/convert/MongoConverters.java#L72]?

See [this](https://stackoverflow.com/questions/37671068/mappinginstantiationexception-with-a-biginteger-field-in-spring-data-couchbase) stackoverflow question

---

**Affects:** 2.1.1 (Hopper SR1)

1 votes, 3 watchers

**Comment by mikereiche** [comment]
#1057 adds a BigInteger Converter

**Comment by mikereiche** [comment]
Please open new issues for specific converters if needed.  Many of the converters mentioned in this issue already exist.
