### ISSUE TITLE
CouchbaseTemplate.doRemove() is not using cas. [DATACOUCH-244]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#557]
**[Young-Gu Chae](https://jira.spring.io/secure/ViewProfile.jspa?name=chaeyk)** opened **[DATACOUCH-244](https://jira.spring.io/browse/DATACOUCH-244?redirect=false)** and commented

I think we should use cas if model of CouchbaseTemplate.remove() parameter has version property

---

**Affects:** 2.1.1 (Hopper SR1), 2.2 M1 (Ingalls)

**Comment by mikereiche** [comment]
The cas is used if provided.
