### ISSUE TITLE
CustomConversions miss collections of applicable objects [DATACOUCH-268]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#580]
**[Eduard Dudar](https://jira.spring.io/secure/ViewProfile.jspa?name=edudar)** opened **[DATACOUCH-268](https://jira.spring.io/browse/DATACOUCH-268?redirect=false)** and commented

I have custom converters defined for `bson.ObjectId` to `String` and back. When I save an object with the following structure:

```java
ObjectId id;
List<ObjectId> refs;
```

I get this document with a singular `ObjectId` field properly converted and `ObjectId` in a list processed as a typical object with getters:

```js
"id": "50d595ec0364e95588c77bd2",
"refs": [
  {
    "timestamp": 1482362407,
    "machineIdentifier": 14170431,
    "processIdentifier": 14086,
    "counter": 9743936,
    "timeSecond": 1482362407,
    "time": 1482362407000,
    "date": 1482362407000
  }
]
```

---

**Affects:** 2.1.5 (Hopper SR5)

**Comment by mikereiche** [comment]
MappingCouchbaseConverter handles this in the read

```
} else if (value instanceof CouchbaseList) {
	map.put(key, readCollection(valueType, (CouchbaseList) value, parent));
```
				
and in the write

```
if (valueType.isCollectionLike()) {
	CouchbaseList collectionDoc = createCollection(asCollection(source), valueType, prop, accessor);
```
