### ISSUE TITLE
Common durability constraints for repository method [DATACOUCH-281]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#593]
**[subhashni balakrishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=subhashni@couchbase.com)** opened **[DATACOUCH-281](https://jira.spring.io/browse/DATACOUCH-281?redirect=false)** and commented

It may be useful to provide this functionality as an annotation for repositories as mostly users would like have the same durability constraints for the entity in a repository

---
No further details from [DATACOUCH-281](https://jira.spring.io/browse/DATACOUCH-281?redirect=false)

**Comment by mikereiche** [comment]
Fixed. See #1063
