### ISSUE TITLE
Spring Data Couchbase documentation page has return type "Long" instead of "long" for count method [DATACOUCH-303]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#613]
**[David Saadeh](https://jira.spring.io/secure/ViewProfile.jspa?name=david.saadeh)** opened **[DATACOUCH-303](https://jira.spring.io/browse/DATACOUCH-303?redirect=false)** and commented

On the Spring Data Couchbase documentation page http://docs.spring.io/spring-data/couchbase/docs/current/reference/html#repositories.core-concepts, under "6.1. Core concepts", in the CrudRepository interface, the return value of the count method is defined as "Long" (object), but I believe it should be the primitive type "long" instead.

---
No further details from [DATACOUCH-303](https://jira.spring.io/browse/DATACOUCH-303?redirect=false)

**Comment by mikereiche** [comment]
it's 'long' now.
