### ISSUE TITLE
Support distinct  in query derivation [DATACOUCH-307]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#616]
**[subhashni balakrishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=subhashni@couchbase.com)** opened **[DATACOUCH-307](https://jira.spring.io/browse/DATACOUCH-307?redirect=false)** and commented

Data commons provides info if the query method has distinct in it. See [DATACMNS-15](https://jira.spring.io/browse/DATACMNS-15)

---

**Affects:** 3.0 M2 (Kay), 2.1.10 (Hopper SR10), 2.2.3 (Ingalls SR3)

**Comment by mikereiche** [comment]
fixed. See #1200.
