### ISSUE TITLE
Integration with Multi-Cluster awareness [DATACOUCH-319]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#630]
**[subhashni balakrishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=subhashni@couchbase.com)** opened **[DATACOUCH-319](https://jira.spring.io/browse/DATACOUCH-319?redirect=false)** and commented

There has been an ask to support multi-cluster in SDC from Perry Krug in Couchbase

---
No further details from [DATACOUCH-319](https://jira.spring.io/browse/DATACOUCH-319?redirect=false)

**Comment by mikereiche** [comment]
we don't peddle MCA any more.
