### ISSUE TITLE
Should spring data couchbase handle list as JsonArray [DATACOUCH-337]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#648]
**[Labusquiere](https://jira.spring.io/secure/ViewProfile.jspa?name=mlab)** opened **[DATACOUCH-337](https://jira.spring.io/browse/DATACOUCH-337?redirect=false)** and commented

I'm expecting :

```java
@Query("#{#n1ql.selectEntity} WHERE (ANY v in externals SATISFIES v.codeSI in $ids END) AND #{#n1ql.filter}")
List<BouquetEntity> myQeury(@Param("ids") JsonArray ids);
```

generate the following :

```sql
SELECT META(`sekai`).id AS _ID, META(`sekai`).cas AS _CAS, `sekai`.* FROM `sekai` WHERE (ANY v in ids SATISFIES v.codeSI in ["value1","value2"] END) AND `_class` = \"ServicePlan::BouquetEntity\"
```

I did try with varargs, array and debug a bit and for me it s today impossible. Am I wrong? is there an other way to do it with `@Query` or it is not supported ?

---

**Affects:** 2.1.11 (Hopper SR11), 2.2.8 (Ingalls SR8), 3.0 GA (Kay)

**Comment by mikereiche** [comment]
https://github.com/spring-projects/spring-data-couchbase/issues/1650 Added converters for JsonNode, JsonObject and JsonArray
