### ISSUE TITLE
Add full text search query interface [DATACOUCH-387]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#657]
**[subhashni balakrishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=subhashni@couchbase.com)** opened **[DATACOUCH-387](https://jira.spring.io/browse/DATACOUCH-387?redirect=false)** and commented

---
No further details from [DATACOUCH-387](https://jira.spring.io/browse/DATACOUCH-387?redirect=false)

**Comment by mikereiche** [comment]
duplicate of https://github.com/spring-projects/spring-data-couchbase/issues/645
