### ISSUE TITLE
Allow querying of documents without _class attribute [DATACOUCH-349]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#663]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATACOUCH-349](https://jira.spring.io/browse/DATACOUCH-349?redirect=false)** and commented

Couchbase repositories always constrain on `_class` when executing queries. Querying a data set that does not have this attribute results in empty results.

It would be great to:

1. Consider `@TypeAlias` annotation
2. Have a configurable field/behavior to use a different field to constrain the type

Maybe aligning type constraints with Spring Data MongoDB would make sense

---

**Issue Links:**
- [DATACOUCH-354](https://jira.spring.io/browse/DATACOUCH-354) CouchbaseRepository.findOne should check _class field

8 votes, 3 watchers

**Comment by mikereiche** [comment]
There is now a TypeAlias annotation. and the getTypeKey() method on AbstractCouchbaseConfigurationCan be overriden. So closing.
