### ISSUE TITLE
Use 'this.' when referencing fields [DATACOUCH-355]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#669]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[DATACOUCH-355](https://jira.spring.io/browse/DATACOUCH-355?redirect=false)** and commented

Whilst looking at Spring Boot issue I noticed that some code doesn't reference private variables using `this`. For example [accessing `operations` in this code](https://github.com/spring-projects/spring-data-couchbase/blob/093073c2ef9eca31b60fe35c610e8a33ba937291/src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java#L122).

For consistency with other Spring projects I think it would be helpful to adopt a uniform style. Spring Boot has a [checkstyle rule](https://github.com/spring-projects/spring-boot/blob/32b817e78d21d79a5c205ca27f9a69dda6ebbd5e/spring-boot-project/spring-boot-parent/src/checkstyle/checkstyle.xml#L63-L66) to enforce this if it helps at all

---
No further details from [DATACOUCH-355](https://jira.spring.io/browse/DATACOUCH-355?redirect=false)

**Comment by mikereiche** [comment]
Spring Boot uses 

```
<module name="com.puppycrawl.tools.checkstyle.checks.coding.RequireThisCheck">
	<property name="checkMethods" value="false" />
	<property name="validateOnlyOverlapping" value="false" />
</module>
```

And the doc https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/RequireThisCheck.html says:
> Warning: the Check is very controversial if 'validateOnlyOverlapping' option is set to 'false' and not that actual nowadays.
