### ISSUE TITLE
@Reference support for object relationship [DATACOUCH-369]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#683]
**[Łukasz Rżanek](https://jira.spring.io/secure/ViewProfile.jspa?name=uded)** opened **[DATACOUCH-369](https://jira.spring.io/browse/DATACOUCH-369?redirect=false)** and commented

As far as I cannot find any details about this implementation I will just go ahead and ask for it.

As I do embrace the embedded structure of JSON storage in Couchbase, sometimes it really does make sense to have a relationship between two objects, and not an embedded data.

It seems that Spring Data is nurturing the concept of `@Reference` annotation, which - according to the documentation I found - does exactly this. On top of that Couchbase seems to support JOINs, which would make a lot of sense to implement in relation to this feature as well

---

1 votes, 2 watchers

**Comment by mikereiche** [comment]
@N1qlJoin does this.
