### ISSUE TITLE
Support Custom design doc name for @ViewIndexed [DATACOUCH-402]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#711]
**[prafsoni](https://jira.spring.io/secure/ViewProfile.jspa?name=prafsoni)** opened **[DATACOUCH-402](https://jira.spring.io/browse/DATACOUCH-402?redirect=false)** and commented

I am facing a situation where I need to add service Id as prefix for designDoc in couchbase to identity which service it belongs too. Since, developers can have same class name in their domain with their own definition across services/packages.

Currently, `@ViewIndexed` is expecting simple java class name as the value of design doc which is very limiting. Since, developer can't always know what class names other developers have used and/or using for active development.

 

---
No further details from [DATACOUCH-402](https://jira.spring.io/browse/DATACOUCH-402?redirect=false)

**Comment by mikereiche** [comment]
> Currently, @ViewIndexed is expecting simple java class name as the value of design doc which is very limiting.

Use @TypeAlias . Note that using something other than the classname means that some other mechanism will need to be available for spring-data-couchbase to know what object to instantiate. (It can use the domain-class for templates, and the entity-class for repositories).
