### ISSUE TITLE
expose CouchbaseTemplate mapToEntity [DATACOUCH-408]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#715]
**[Jochem van Dieten](https://jira.spring.io/secure/ViewProfile.jspa?name=jochemd)** opened **[DATACOUCH-408](https://jira.spring.io/browse/DATACOUCH-408?redirect=false)** and commented

Some operations, such as locking, currently require getting the underlying Bucket from the Couchbase Java SDK and performing the operations directly on it. For many operations the result is a Couchbase Document, instead of a Spring Entity. To convert from the Document to the Entity we need to create a converter and replicate the Couchbase configuration and the Couchbase custom conversions to it.

The conversion of the document to an entity would be more convenient / efficient if we could just reuse the entity mapper functionality that is present in the CouchbaseTemplate

---
No further details from [DATACOUCH-408](https://jira.spring.io/browse/DATACOUCH-408?redirect=false)

**Comment by mikereiche** [comment]
getAndLock is now supported.


For writing :

CouchbaseDocument entityDoc = new CouchbaseDocument(entity.getId());
mappingCouchbaseConverter.write(entity, entityDoc);
collection.insert( entityDoc.getId(), entityDoc.export());
	
For reading - 

support.decodeEntity(id, result.contentAs(String.class), result.cas(), domainType, 	null, null, null, null)
