### ISSUE TITLE
Better document reference linking support through spring-data-rest  [DATACOUCH-416]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#724]
**[ronnc](https://jira.spring.io/secure/ViewProfile.jspa?name=ronnc)** opened **[DATACOUCH-416](https://jira.spring.io/browse/DATACOUCH-416?redirect=false)** and commented

See an example below where Address is an associated entity to a Person.

https://docs.spring.io/spring-data/rest/docs/current/reference/html/#projections-excerpts.projections

As far as I can see, we can't do this with spring-data-couchbase and what I have to do is create a bespoke reference wrapper object that holds that reference and document and then have serialise HAL _link url manually. This works okay but projection concept in spring-data-rest is much more powerful patter that provide ability to control what attributes you want to serialise and when you want to use certain projection.

 

Surely linking documents together is a common usage pattern. I can't find any discussion forum for spring-data-couchbase. Has there been any discussion about this? Is there anywhere that this feature could be discussed?

 

 

 

---
No further details from [DATACOUCH-416](https://jira.spring.io/browse/DATACOUCH-416?redirect=false)

**Comment by mikereiche** [comment]
This is implemented with @N1qlJoin
