### ISSUE TITLE
Allow to configure username and password at cluster level config [DATACOUCH-423]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#732]
**[subhashni balakrishnan](https://jira.spring.io/secure/ViewProfile.jspa?name=subhashni@couchbase.com)** opened **[DATACOUCH-423](https://jira.spring.io/browse/DATACOUCH-423?redirect=false)** and commented

Currently authentication info has to be provided per bucket on SDC properties, it would be useful to provide cluster level configurable parameters when multiple buckets use the same authentication

---
No further details from [DATACOUCH-423](https://jira.spring.io/browse/DATACOUCH-423?redirect=false)

**Comment by himanshumps** [comment]
Any updates on this ?

@davidkelly @bsubhashni

**Comment by mikereiche** [comment]
Since 4.0, one configuration is used on all buckets.
