### ISSUE TITLE
Support JSR303 Validation in ReactiveCouchbaseRepository [DATACOUCH-496]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#765]
**[Leonardo Duarte](https://jira.spring.io/secure/ViewProfile.jspa?name=l30thelion@yahoo.com)** opened **[DATACOUCH-496](https://jira.spring.io/browse/DATACOUCH-496?redirect=false)** and commented

It would be nice to have JSR303 Validation support in ReactiveCouchbaseRepository:

 

Hello, I'm using spring-data-couchbase's `ReactiveCouchbaseRepository` and it seems there isn't support for using JSR303 validation (though there is in the non-reactive counterpart via event listener). I was wondering if there is a reason why it isn't supported, curious if maybe it hasn't been implemented cause it doesn't make sense maybe? I played around with a naive implementation of it by modifying `RxJavaCouchbaseTemplate` and was wondering if it would be possible to get feedback on it.

https://github.com/spring-projects/spring-data-couchbase/compare/master...l30thelion:master

 

Excerpt in RxJavaCouchbaseTemplate:

```java
private <T> Observable<T> doPersist(T objectToPersist, PersistType persistType, PersistTo persistTo, ReplicateTo replicateTo) {
        validateBeforePersist(objectToPersist);  // add validation here??
        // If version is not set - assumption that document is new, otherwise updating
        Long version = getVersion(objectToPersist);
        Func3<RawJsonDocument, PersistTo, ReplicateTo, Observable<RawJsonDocument>> persistFunction;
```

 

Add in RxJavaCouchbaseTemplate:

```java
    public void setValidator(final Validator validator) {
        this.validator = validator;
    }

    private <T> void validateBeforePersist(T objectToPersist) {
        if (validator != null) {
            Set violations = validator.validate(objectToPersist);
            if (!violations.isEmpty()) {
                throw new ConstraintViolationException(violations);
            }
        }
    }
```

 

Usage in my project opting-in by adding a validator from the context:

```java
@Configuration(proxyBeanMethods = false)
class CouchbaseConfiguration {

    @Bean(name = [BeanNames.RXJAVA1_COUCHBASE_TEMPLATE])
    fun reactiveCouchbaseTemplate(
            @Qualifier("springBootCouchbaseConfigurer") couchbaseConfigurer: CouchbaseConfigurer,
            mappingCouchbaseConverter: MappingCouchbaseConverter,
            translationService: TranslationService,
            validator: Validator? // javax.validation.Validator
    ): RxJavaCouchbaseTemplate? {
        val template = RxJavaCouchbaseTemplate(
                couchbaseConfigurer.couchbaseClusterInfo(),
                couchbaseConfigurer.couchbaseClient(),
                mappingCouchbaseConverter,
                translationService)
        // opt-in to use validation
        template.setValidator(validator)
        return template
    }

}
```

---

**Affects:** 3.2.3 (Moore SR3)

**Comment by mikereiche** [comment]
This is present.  See https://github.com/spring-projects/spring-data-couchbase/issues/1224
