### ISSUE TITLE
Ability to append mutliple attributes along with `_class` to each query [DATACOUCH-464]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#774]
**[UmairYasin](https://jira.spring.io/secure/ViewProfile.jspa?name=umairyasin)** opened **[DATACOUCH-464](https://jira.spring.io/browse/DATACOUCH-464?redirect=false)** and commented

 I am using document based multi tenant approach where each document in couchbase db have tenant-ID field. Now for all the queries that are executing in my application, i want extend tenant-ID to it which is present in Session Context
One solution is to manually add the tenant-id clause to every query but this solution is not very optimal as i want to enforce that no query in applicaion should be executed without tenant-id.

There should be a way to extend couchbase base configuration to add tenant-id like the same way it is adding _class attribute to every query

---

**Affects:** 3.1.9 (Lovelace SR9)

**Comment by mikereiche** [comment]
scope should be used to separate tenant data.

**Comment by mikereiche** [comment]
>  i want to enforce that no query in applicaion should be executed without tenant-id

That is not sufficient for compartmentalizing data. Data should be compartmentalized with authorization, not just a convention.
