### ISSUE TITLE
Allow spring data couchbase annotations to be used in meta-annotation context [DATACOUCH-495]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#805]
**[Garret Fick](https://jira.spring.io/secure/ViewProfile.jspa?name=garretfick)** opened **[DATACOUCH-495](https://jira.spring.io/browse/DATACOUCH-495?redirect=false)** and commented

As a developer, I want to be able to easily choose between using Couchbase or other simplar repositories that all use the same document and change the implementing repository at runtime, for example by profile configuration. This can be achieved by adding annotations required by each repository implementation to each field in the document.

 

For example, if I wanted to support both Couchbase and DynamoDB, I might have the following

 

```java
class Entity {

   @Id
   @DynamoDBHashKey
   @DynamoDBAutoGeneratedKey
   public String id;

   @Field
   @DynamoDBAttribute
   public String field1;

   @Field
   @DynamoDBAttribute
   public String field2;
}

```

The annotation on the field is repetitive. (The same idea applies to the ID if I have multiple entity definitions).

 

To eliminate the repetition and reduce the opportunity for defects, I would like to be able to define my own annotation, for example:

```java
 @Id
 @DynamoDBHashKey
 @DynamoDBAutoGeneratedKey
 @Retention(RetentionPolicy.RUNTIME)
 @Target({ ElementType.FIELD })
 public @interface MyId {}

AND

 @Field
 @DynamoDBAttribute
 public @interface MyField {}
```

 

Then, I an write the simpler

 

```java
class Entity {

 @MyId
 public String id;

 @MyField
 public String field1;

 @MyField
 public String field2;
}
 
```

This is currently not possible because the target for the annotations only permits fields, but it is trivial to change.

 

**NOTE** While this is not my current use case, it would also be possible to use this capability to create combinations that include JSR 380 annotations (for example `@NotNull`), again for the objective of not repeating yourself.

 

---
No further details from [DATACOUCH-495](https://jira.spring.io/browse/DATACOUCH-495?redirect=false)

**Comment by mikereiche** [comment]
The couchbase @Field (and other annotations) have Target of ANNOTATION_TYPE, so you can indeed build your own annotations.

@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.ANNOTATION_TYPE })
