### ISSUE TITLE
Review WriteResultChecking default, usage, documentation [DATACOUCH-497]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#806]
**[David Kelly](https://jira.spring.io/secure/ViewProfile.jspa?name=kelly)** opened **[DATACOUCH-497](https://jira.spring.io/browse/DATACOUCH-497?redirect=false)** and commented

So by default, we don't raise any exceptions when a `repository.save()` fails, apart from a couple CAS-related possibilities.  Our options are NONE or EXCEPTION as well -- perhaps we should have LOG as well?  Lets ponder adding LOG for sure.

Also - do we really want NONE as the default?  That seems.... wrong to me.  But lets review others (MongoDB does default to NONE, but maybe they are an exception?), and decide.  Good to do this as part of 4.0.x since it maybe will be a surprise to existing users.

Lets also review the documentation on this, and insure this is much more obvious to our users

---
No further details from [DATACOUCH-497](https://jira.spring.io/browse/DATACOUCH-497?redirect=false)

**Comment by mikereiche** [comment]
Any exception encountered during repository.save() is thrown.
