### ISSUE TITLE
N1QLJoin on reactive implementation [DATACOUCH-527]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#835]
**[Juan Pablo Escobedo](https://jira.spring.io/secure/ViewProfile.jspa?name=hohenheimsemberg)** opened **[DATACOUCH-527](https://jira.spring.io/browse/DATACOUCH-527?redirect=false)** and commented

RxJavaCouchbaseTemplate.mapToEntity does not have implemented N1QLJoin, CouchbaseTemplate does.

Or at least it should be pointed in the spring reference.[More](https://jira.spring.io/projects/DATACOUCH/issues/DATACOUCH-527?filter=allissues#)

---
No further details from [DATACOUCH-527](https://jira.spring.io/browse/DATACOUCH-527?redirect=false)

**Comment by mikereiche** [comment]
see #1198
