### ISSUE TITLE
Add support for AfterConvertEvent [DATACOUCH-537]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#845]
**[deniswsrosa](https://jira.spring.io/secure/ViewProfile.jspa?name=deniswsrosa)** opened **[DATACOUCH-537](https://jira.spring.io/browse/DATACOUCH-537?redirect=false)** and commented

Add a similar behavior to Mongo's AfterConvertEvent (https://docs.spring.io/spring-data/data-mongodb/docs/current/api/org/springframework/data/mongodb/core/mapping/event/AfterConvertEvent.html)

This feature is a request of a developer: https://twitter.com/vijvij123/status/1258753267665760256

---
No further details from [DATACOUCH-537](https://jira.spring.io/browse/DATACOUCH-537?redirect=false)

**Comment by mikereiche** [comment]
There is an afterConvertCallback.
