### ISSUE TITLE
Repository throws error while returning VO [DATACOUCH-549]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#857]
**[deniswsrosa](https://jira.spring.io/secure/ViewProfile.jspa?name=deniswsrosa)** opened **[DATACOUCH-549](https://jira.spring.io/browse/DATACOUCH-549?redirect=false)** and commented

Given the following entity:

 

```java
@Document
@Data
@ToString
public class User {

 @Id
 private String id;
 private String name;
 private String position;
 private String description;
 private double accountBalance;
}
```

The following VO:

```java
@Data
public class UserVO {
 private String name;
 private String position;
}
```

And this repository:

```java
@Repository
public interface UserRepository extends CouchbaseRepository<User, String> {
 List<UserVO> findByName(String name);
}
```

 

If I try to run the following code:

```java
List<UserVO> users = userRepository.findByName("Bruce");
```

This exception is thrown

**Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.example.sp3.User] to type [com.example.sp3.UserVO]Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.example.sp3.User] to type [com.example.sp3.UserVO] at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)**

 

With SPC3 the same code works ok.

 

 

 

 

 

 

 

---

**Affects:** 4.0 GA (Neumann)

**Comment by mikereiche** [comment]
This could/should be done with 'as' in the fluent api:

List<UserVO> users = userRepository.findByName("Bruce");
