### ISSUE TITLE
AutoIndexing is not Working properly [DATACOUCH-550]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#858]
**[deniswsrosa](https://jira.spring.io/secure/ViewProfile.jspa?name=deniswsrosa)** opened **[DATACOUCH-550](https://jira.spring.io/browse/DATACOUCH-550?redirect=false)** and commented

I have enabled autoindexing according to the docs:

```java
@Configuration
public class Config extends AbstractCouchbaseConfiguration {


 @Override
 public String getConnectionString() {
 return "couchbase://127.0.0.1";
 }

 @Override
 public String getUserName() {
 return "Administrator";
 }

 @Override
 public String getPassword() {
 return "password";
 }

 @Override
 public String getBucketName() {
 return "default";
 }


 /**
 * OPTIONAL: In this example we are using annotations to
 */

 @Override
 protected boolean autoIndexCreation() {
 return true;
 }
}
```

 

And here is my entity:

 

```java
@Document
@Data
@ToString
@CompositeQueryIndex(fields = {"id", "name", "position"})
public class User {

 @Id
 private String id;
 @QueryIndexed
 private String name;
 @QueryIndexed
 private String position;
 private String description;
 private double accountBalance;
}
```

 

I have tried many variations of the mapping above, and after the application starts no index is created on the target bucket.

 

 

 

 

 

---

**Affects:** 4.0 GA (Neumann)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-couchbase/pull/295

1 votes, 5 watchers

**Comment by mikereiche** [comment]
Fixed in 
https://github.com/spring-projects/spring-data-couchbase/commit/03ad3697ae04eddc6346bcdeecd90912c6208c7e

And that was superseded with 
https://github.com/spring-projects/spring-data-couchbase/commit/80bae4bf67c8deb78fa9cef5c685335b62f16efd
