### ISSUE TITLE
Projections generate queries with Select * [DATACOUCH-552]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#860]
**[deniswsrosa](https://jira.spring.io/secure/ViewProfile.jspa?name=deniswsrosa)** opened **[DATACOUCH-552](https://jira.spring.io/browse/DATACOUCH-552?redirect=false)** and commented

Even when the returned object is a ValueObject (VO) with just a subset of the attributes of the original entity, the underlying generated query is always a *select ** : 

```java
SELECT META(`test`).id AS _ID, META(`test`).cas AS _CAS, `test`.* FROM `test` WHERE (`name` = $1 AND `address`.`city` = $2) AND `_class` = \"com.example.usertest.Product\""
```

Ideally, we should analyze the return type first, and generate the query using just the attributes present in the ValueObject. Example:

Given the following VO:

 

```java
public class ProductVO {
   private String name;
   private String description;
}
```

 

 

And the following query:

 

```java
List<ProductVO> findByNameAndAddress_City(String name, String city);
```

 

The generated query should be similar to:

 

```java
SELECT META(`test`).id AS _ID, META(`test`).cas AS _CAS, `test`.name, `test`.descrition  FROM `test` WHERE (`name` = $1 AND `address`.`city` = $2) AND `_class` = \"com.example.usertest.Product\""
 
```

 

This can potentially solve performance issues we have in some scenarios with the SpringData SDK and leverage cover indexes as we are only returning the necessary attributes.

**NOTE:** I haven’t checked the current behavior on SPC4 because of another bug. But that is the desired behavior on SPC3

---

**Affects:** 4.0 GA (Neumann)

**Comment by mikereiche** [comment]
fixed.
