### ISSUE TITLE
Missing couchbase.repository.multibucket documentation (4.x) [DATACOUCH-570]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#878]
**[Guillaume Durandiere](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49747)** opened **[DATACOUCH-570](https://jira.spring.io/browse/DATACOUCH-570?redirect=false)** and commented

There is a link about the multibucket configuration in the following documentation (4.0.1) : https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.repository.multibucket

But there is nothing about it.

Will you add it soon ?

 

---

**Affects:** 4.0.1 (Neumann SR1)

**Comment by mihaidi** [comment]
Hello @mikereiche one question I need to connect to multiple buckets inside same Cluster but I need to do this dynamically based on data from application.yaml also I don't need to use any Entity objects I want to query using CouchbaseTemplate and operate with json response is this even posible , thanks in advance

**Comment by mikereiche** [comment]
Mapping is by entity type only.

**Comment by mihaidi** [comment]
> Mapping is by entity type only.

Well look like no , I figure out a solution and now I operate with multiple buckets without any Entity objects only with JSON string response.

**Comment by mikereiche** [comment]
"I figure out a solution and now I operate with multiple buckets without any Entity objects only with JSON string response"

Ok, so what is the issue?

**Comment by moriyahazan** [comment]
hey, i implemented mulibucket as explained in this thread, it works. thanks 
Now i have a question about [Custom Converters](https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#datatypes) it is working only for default bucket and not for all other buckets, any idea add convertor for all buckets? 
thank in advanced

**Comment by mikereiche** [comment]
Refer to the example - instead of providing  a new MappingCouchbaseConverter(), provide your custom couchbase converter.

  CouchbaseTemplate userTemplate = myCouchbaseTemplate(myCouchbaseClientFactory("mybucket"),new MappingCouchbaseConverter());

**Comment by moriyahazan** [comment]
@mikereiche thanks for your reply

i have following convertor:
 ```

  @Override
    public CouchbaseCustomConversions customConversions() {
        return new CouchbaseCustomConversions(Arrays.asList(
                ZonedDateTimeToEpochTimeConverter.INSTANCE,
                EpochTimeToZonedDateTimeConverter.INSTANCE));
    }


    @WritingConverter
    public enum ZonedDateTimeToEpochTimeConverter implements Converter<ZonedDateTime, CouchbaseDocument> {
        INSTANCE;

        @Override
        public CouchbaseDocument convert(ZonedDateTime zonedDateTime) {
            CouchbaseDocument cd = new CouchbaseDocument();
            cd.put(EPOC_MILLI, zonedDateTime.toInstant().toEpochMilli());
            cd.put(OFFSET_SECONDS, zonedDateTime.getOffset().getTotalSeconds());
            return cd;
        }
    }

    @ReadingConverter
    public enum EpochTimeToZonedDateTimeConverter implements Converter<CouchbaseDocument, ZonedDateTime> {
        INSTANCE;

        @Override
        public ZonedDateTime convert(CouchbaseDocument epochTime) {
            long timeMilli = Long.parseLong(epochTime.getContent().get(EPOC_MILLI).toString());
            int offsetSeconds = Integer.parseInt(epochTime.getContent().get(OFFSET_SECONDS).toString());

            ZoneOffset convertedOffset = ZoneOffset.ofTotalSeconds(offsetSeconds);
            return ZonedDateTime.ofInstant(Instant.ofEpochMilli(timeMilli), convertedOffset);
        }
    }
```
i set this converter inside mapping
```
MappingCouchbaseConverter mappingCouchbaseConverter = new MappingCouchbaseConverter();
mappingCouchbaseConverter.setCustomConversions(customConversions());
baseMapping.mapEntity(Class.forName(beanDefinition.getBeanClassName()),myCouchbaseTemplate(myCouchbaseClientFactory("mybucket"),mappingCouchbaseConverter ));

```
But i am getting below exception when save the doc although there is convertor from zonedatetime to couchebasedocument
 ```
2021-05-27 17:29:27.178 ERROR 18916 --- [nio-9001-exec-1] g.k.e.error.DefaultGraphQLErrorHandler   : Error executing query Exception while fetching data (/createProduct) : No converter found capable of converting from type [java.time.ZonedDateTime] to type [org.springframework.data.couchbase.core.mapping.CouchbaseDocument]

org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.time.ZonedDateTime] to type [org.springframework.data.couchbase.core.mapping.CouchbaseDocument]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[spring-core-5.3.5.jar:5.3.5]
	at org.springframework.data.couchbase.core.convert.MappingCouchbaseConverter.lambda$getPotentiallyConvertedSimpleWrite$2(MappingCouchbaseConverter.java:784) ~[spring-data-couchbase-4.1.6.jar:4.1.6]
	at java.base/java.util.Optional.map(Optional.java:265) ~[na:na]
	at org.springframework.data.couchbase.core.convert.MappingCouchbaseConverter.getPotentiallyConvertedSimpleWrite(MappingCouchbaseConverter.java:784) ~[spring-data-couchbase-4.1.6.jar:4.1.6]
	at org.springframework.data.couchbase.core.convert.MappingCouchbaseConverter.writeSimpleInternal(MappingCouchbaseConverter.java:774) ~[spring-data-couchbase-4.1.6.jar:4.1.6]
	at org.springframework.data.couchbase.core.convert.MappingCouchbaseConverter.access$200(MappingCouchbaseConverter.java:82) ~[spring-data-couchbase-4.1.6.jar:4.1.6]
	
```
Can you please help?

**Comment by mikereiche** [comment]
Please create a new issue. @moriyahazan

**Comment by moriyahazan** [comment]
please see
https://github.com/spring-projects/spring-data-couchbase/issues/1141

**Comment by mikereiche** [comment]
@moriyahazan - I'm not sure if this is your issue, 

mappingCouchbaseConverter.setCustomConversions(customConversions());

But don't use the same name as the existing @Bean method as the spring framework replaces calls to methods with the value of matching @Bean methods.

	@Bean(name = BeanNames.COUCHBASE_CUSTOM_CONVERSIONS)
	public CustomConversions customConversions() {
		return new CouchbaseCustomConversions(Collections.emptyList());
	}
	
This is why in my examples I always prefix the methods with "my"

**Comment by moriyahazan** [comment]
@mikereiche I tried to use special name for converter but issue still persist
please see code in https://github.com/moriyahazan/designer-service

thanks!

**Comment by mikereiche** [comment]
Please see my response on #1141

**Comment by martinprobson** [comment]
Just an extra note as Google brought me here when I searched for multi-bucket configuration. 

These instructions worked perfectly, except the Couchbase auditing support (via `@EnableCouchbaseAuditing` annotation) stopped working. To re-enable I just had to set the application context on the userTemplate object (see 'Extra line' below).

```java
@Override 
public void configureReactiveRepositoryOperationsMapping(ReactiveRepositoryOperationsMapping baseMapping) {
 try {
  ReactiveCouchbaseTemplate personTemplate = myReactiveCouchbaseTemplate(myCouchbaseClientFactory("protected"),new MappingCouchbaseConverter());
  baseMapping.mapEntity(Person.class,  personTemplate); // Person goes in "protected" bucket
  ReactiveCouchbaseTemplate userTemplate = myReactiveCouchbaseTemplate(myCouchbaseClientFactory("mybucket"),new MappingCouchbaseConverter());
  userTemplate.setApplicationContect(applicationContext)  // <----- Extra line
  baseMapping.mapEntity(User.class,  userTemplate); // User goes in "mybucket"
  // everything else goes in getBucketName() 
 } catch (Exception e) {
  throw e;
 }
}
````

**Comment by premvarmak** [comment]
Hi... I am trying to connect to multiple clusters using Spring Data Couchbase. Is there a possibility to it at this moment ?
I have copied AbstractCouchbaseConfiguration and created a new class with different bean names. 

With this connecttion is created to this new cluster but the repository is not getting that connection through CrudRepository. Is there a way to do it ?

**Comment by mikereiche** [comment]
The selection is made on the entity class. You'll need to make another repository interface based on the other entity class.  If you still have issues, post the repository classes, the entity classes, the config class and the code that calls the repository methods so I can reproduce it.

**Comment by premvarmak** [comment]
Thank you for the prompt response. Here is my requirement. I want to have one Spring Boot App which connects to multiple couchbase DBs. So basically...

Couchbase Cluster 1 (_This I was able to achieve it by following your comment above_)
         Bucket 1
         Bucket 2

Now I want to have another cluster in the same app. where am facing issue.
Couchbase Cluster 2
         Bucket 1
         Bucket 2

Here is the link to my code: https://github.com/premvarmak/spring-pvk-data-couchbase/tree/master

I have added readme file explaining the setup. But its a very basic setup which I have created following the Spring documentation.

**Comment by premvarmak** [comment]
[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)
Any pointers in this direction ?  In the codebase I have provided, 

I have override CouchbaseTemplate to provide new cluster and bucket information and marked it under new Bean. Than I override configureRepositoryOperationsMapping. **And I am able to get two couchbase instances registered but I am not able to attach this new instance configuration with repositories.**

**Comment by mikereiche** [comment]
Run with the debugger and set a break-point in the implementation of CouchbaseOperations.resolve().

**Comment by mikereiche** [comment]
" And I am able to get two couchbase instances registered but I am not able to attach this new instance configuration with repositories."

In your project, couchbaseTemplate() is not overridden.

```
public class NephosCbConfig extends AbstractCouchbaseConfiguration {

    @Value("${couchbase.bootstrap-hosts}")
    private String connectionString;
    @Value("${couchbase.username}")
    private String userName;
    @Value("${couchbase.password}")
    private String password;
    @Value("${couchbase.bucket}")
    private String bucketName;
    @Value("${couchbase.bucket2}")
    private String travelSampleBucket;

    @Override
    public String getConnectionString() {
        return connectionString;
    }

    @Override
    public String getUserName() {
        return userName;
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public String getBucketName() {
        return bucketName;
    }

    /* Multi bucket configuration START */
    @Override
    public void configureRepositoryOperationsMapping(RepositoryOperationsMapping baseMapping) {
        try {
            CouchbaseTemplate travelSampleTemplate = myCouchbaseTemplate(myCouchbaseClientFactory(travelSampleBucket),new MappingCouchbaseConverter());
            baseMapping.mapEntity(TravelSample.class,  travelSampleTemplate); // TravelSample mapped to "travel-sample" bucket

        } catch (Exception e) {
            throw e;
        }
    }

    public CouchbaseTemplate myCouchbaseTemplate(CouchbaseClientFactory couchbaseClientFactory,
                                                 MappingCouchbaseConverter mappingCouchbaseConverter) {
        return new CouchbaseTemplate(couchbaseClientFactory, mappingCouchbaseConverter);
    }

    public CouchbaseClientFactory myCouchbaseClientFactory(String bucketName) {
        return new SimpleCouchbaseClientFactory(getConnectionString(), authenticator(), bucketName );
    }
    /* Multi bucket configuration END */
}
```

**Comment by premvarmak** [comment]
Yeah!!! I am able to connect to multiple clusters now... 

Your point _"The selection is made on the entity class."_ Based on this, I created multiple CouchbaseTemplate and mapped respective entities in RepositoryOperationsMapping. And then all is working good... 

[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche) Thank you for your time :)

**Comment by mikereiche** [comment]
That's great @premvarmak.
Can I use your application as an example to add to the documentation? Is it in the repository posted above?

**Comment by premvarmak** [comment]
The change is my local. I will commit to the above repository and will let you know here. Thank you...

**Comment by premvarmak** [comment]
[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)

https://github.com/premvarmak/spring-pvk-data-couchbase/blob/master/README.md
