### ISSUE TITLE
ReactiveCouchbaseRepositoryKeyValueIntegrationTests fails against 7.0 2518 [DATACOUCH-584]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#892]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-584](https://jira.spring.io/browse/DATACOUCH-584?redirect=false)** and commented

The server is being ran via vagrant - this might be causing some delay. 

[*ERROR*]   **ReactiveCouchbaseRepositoryQueryIntegrationTests.count:115 expected: <7> but was: <0>**

 

**With the sleep() at 1 second, the count returned is 0.**

**Increasing the sleep() from 1 second to 5 seconds results in the count being 2****

**Increasing the sleep() from 1 second to 10 seconds results in the correct count of 7 being returned.**

for (int i = 0; i < iatas.length; i++) {
Airport airport = new Airport("airports::" + iatas[i], iatas[i] /**iata**/, iatas[i].toLowerCase() /* lcao */);
airportRepository.save(airport).block();
}
try {
Thread.sleep(1000);
} catch (InterruptedException ie) {}
Long airportCount = null;
airportCount = airportRepository.count().block();
assertEquals(7, airportCount);

---
No further details from [DATACOUCH-584](https://jira.spring.io/browse/DATACOUCH-584?redirect=false)

**Comment by mikereiche** [comment]
This is expected.  "count" is actually a query and would require REQUEST_PLUS.
