### ISSUE TITLE
some repository methods ignore ScanConsistency annotation [DATACOUCH-585]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#893]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-585](https://jira.spring.io/browse/DATACOUCH-585?redirect=false)** and commented

SimpleReactiveCouchbaseRepository count() is missing the consistentWith(buildQueryScanConsistency() which can be found in findAll(Query q).

consistentWith() is not relevant to any other queries which operate on the id (findById(), findAllById(),  upsertById, deleteById ).    ReactiveRemoveByQuery already leverages consistentWith(). 

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-couchbase/pull/247

**Comment by mikereiche** [comment]
N1qlRepositoryQueryExecutor has been deprecated.
