### ISSUE TITLE
Save() operation doesn't seem to be synchronous [DATACOUCH-589]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#897]
**[murdos](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49841)** opened **[DATACOUCH-589](https://jira.spring.io/browse/DATACOUCH-589?redirect=false)** and commented

Using a non reactive repository, the following code in an integration test randomly fail, which make me think that then entity is not always saved when the save() method returns:

```java
// Initialize the database
userRepository.save(user);
int databaseSizeBeforeCreate = userRepository.findAll().size();

assumeThat(databaseSizeBeforeCreate).isEqualTo(1); // assumption randomly fail with databaseSizeBeforeCreate being equal to 0
```

---

**Affects:** 4.1 M2 (2020.0.0)

**Comment by mraible** [comment]
@mikereiche I'm trying to pick up where @murdos left off and upgrade JHipster's Couchbase support to work with Spring Boot 2.4.2. You can see my [in-progress PR here]().

I feel like I'm overriding methods all over and added the following everywhere.

```java
@ScanConsistency(query = QueryScanConsistency.REQUEST_PLUS)
```

However, I only really need this for tests, so it seems kinda weird.

Is there a mechanism in Spring Data Couchbase to make things strongly consistent like previous versions had? I'd only like it for tests so we can add/retrieve data successfully.

From https://stackoverflow.com/q/54897120/65681:

```java
@TestConfiguration
@Slf4j
@Order(0)
public class TestCouchbaseConfig extends AbstractCouchbaseConfiguration {

    ...

    @Override
    protected Consistency getDefaultConsistency() {
        return Consistency.STRONGLY_CONSISTENT; //READ_YOUR_OWN_WRITES|UPDATE_AFTER ... etc;
    }
}
```

**Comment by mikereiche** [comment]
The getDefaultConsistency() method is gone from the AbstractCouchbaseConfiguration. I don't know why.
It could be added back, or we could introduce a Class-level \@ScanConsistency annotation.

**Comment by mraible** [comment]
In my experience with JHipster, we only need it for testing, so setting it globally in one place (e.g., a test configuration class) is my favorite option. I'm not sure we need it on the method or class level because all our e2e tests (with Cypress) pass w/o it.
