### ISSUE TITLE
org.springframework.data.couchbase.core.query.Query.export() s/b deprecated [DATACOUCH-598]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#906]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-598](https://jira.spring.io/browse/DATACOUCH-598?redirect=false)** and commented

org.springframework.data.couchbase.core.query.Query.export() should be deprecated - the only place it is used is in tests - where it uses a null value for parameterPtr instead of a one-element array.

toN1qlString() should be used instead.  parameterPtr should be a one-element array and the expected output should have place-holders ($1) instead of literals.

There is a similar issue with Criteria.export().  It is used in tests without a parameter, but it always called with a parameter in spring

---
No further details from [DATACOUCH-598](https://jira.spring.io/browse/DATACOUCH-598?redirect=false)

**Comment by mikereiche** [comment]
It's also used to print out the query in human readible form.

toN1qlString() is deprecated.

criteria.export() is used to print out the criteria in readable form.
