### ISSUE TITLE
fix issue with id in nested objects caused by DATACOUCH-533 [DATACOUCH-620]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#928]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-620](https://jira.spring.io/browse/DATACOUCH-620?redirect=false)** and commented

[DATACOUCH-533](https://jira.spring.io/browse/DATACOUCH-533) assumes fields named 'id' are document id's. As such they are removed from the data to be used as the "key".   
When a nested document - such as Submission in the User object - contains an 'id', it is also removed from the data.

public class User {
  private String id;
  private String username;
  private List\<Submission> submissions;
}

public class Submission {
  private final String id;
  private final String userId;
  private final String talkId;
}

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-couchbase/pull/266

**Backported to:** [4.0.5 (Neumann SR5)](https://github.com/spring-projects/spring-data-couchbase/milestone/164?closed=1)

1 votes, 3 watchers

**Comment by martin8877** [comment]
Hi, 
Has this issue been resolved?

**Comment by chokirock** [comment]
Just as info, we updated our project to Spring Boot 2.3.7 (Spring Data Couchbase 4.0.6 released on December) and still facing same issue when retrieving embedded object id.

In the meantime as a workaround we applied @mikereiche approach using an all-args constructor for the embedded object.

**Comment by mikereiche** [comment]
part of this issue that remained - DATACOUCH-620 - is fixed in 4.1.3

MappingCouchbaseConverter - Line 270
https://github.com/spring-projects/spring-data-couchbase/commit/3364e0fa7f8d5cb9200abac820312f7a28d4c41d#diff-fe5ee5c3b9e5ec163fde2c91c9d6e98b53296201957903dacc0479bddf95c7d7
