### ISSUE TITLE
Docs still shows version 4.0.0.RELEASE [DATACOUCH-653]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#931]
**[deniswsrosa](https://jira.spring.io/secure/ViewProfile.jspa?name=deniswsrosa)** opened **[DATACOUCH-653](https://jira.spring.io/browse/DATACOUCH-653?redirect=false)** and commented

The current documentation still shows version 4.0.0.RELEASE even though the current version is [4.1.1](https://mvnrepository.com/artifact/org.springframework.data/spring-data-couchbase/4.1.1)

https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#reference

---
No further details from [DATACOUCH-653](https://jira.spring.io/browse/DATACOUCH-653?redirect=false)

**Comment by mikereiche** [comment]
Now it shows 4.1.1. It needs to show 4.2.4

https://spring.io/projects/spring-data-couchbase
