### ISSUE TITLE
CouchbasePersistentEntity#isTouchOnRead never used? [DATACOUCH-629]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#940]
**[David Prevost](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50500)** opened **[DATACOUCH-629](https://jira.spring.io/browse/DATACOUCH-629?redirect=false)** and commented

I was checking to use the expiry feature and I noticed that we can configure the touchAndRead on Document#touchOnRead.

However, even though it is read by CouchbasePersistentEntity#isTouchOnRead, no one is actually checking if the entity expiry date need to be touchAndRead.

By analysing MappingCouchbaseConverter#writeInternal(), we can see that the expiry is always updated instead of doing it by checking if the touchAndRead is activated... unless this is a feature of JPA then is it probably a bug.

Fortunately for me, I need the expiry to be updated so not a major bug for me...

---
No further details from [DATACOUCH-629](https://jira.spring.io/browse/DATACOUCH-629?redirect=false)

**Comment by mikereiche** [comment]
Thanks for your input.  Will handle this in
https://github.com/spring-projects/spring-data-couchbase/issues/982
