### ISSUE TITLE
Add @EnableReactiveCouchbaseAuditing  [DATACOUCH-644]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#955]
**[hantsy](https://jira.spring.io/secure/ViewProfile.jspa?name=hantsy1)** opened **[DATACOUCH-644](https://jira.spring.io/browse/DATACOUCH-644?redirect=false)** and commented

In this new Spring Data commons, there is a new ReactiveAuitorAware added for reactive stack.

The R2dbc, Mongo, Neo4j, etc had added a variant to enable this support.

Suggest use  `@EnableReactiveCouchbaseAuditing` to enable it

---

**Affects:** 4.1 GA (2020.0.0)

**Reference URL:** https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-couchbase

**Comment by jorgerod** [comment]
Hi

What is the status of this issue?
I could try to contribute.

**Comment by mikereiche** [comment]
@jorgerod - auditing can be enabled with  EnableAuditorAware .  It is for both reactive and non-reactive operations. Let me know if more is required

**Comment by jorgerod** [comment]
Hi @mikereiche 

I think it would be useful to be able to use `org.springframework.data.domain.ReactiveAuditorAware`, like spring-data-mongo does.

Specifically, I want to make a ReactiveAuditorAware to audit the spring-security user that is obtained from ReactiveSecurityContextHolder which in a reactive application is a Mono.


*Sample*
```java
public class ReactiveSecurityCouchbaseAuditorAware implements ReactiveAuditorAware {

    @Override
    public Mono<String> getCurrentAuditor() {
        return ReactiveSecurityContextHolder.getContext()
                   .map(securityContext -> securityContext.getAuthentication().getName());
   }
}
```

What do you think?

**Comment by mikereiche** [comment]
@jorgerod if you make a pull-request, I'll submit it.
