### ISSUE TITLE
AuditorAware and DateTimeProvider regression [DATACOUCH-647]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-couchbase#958]
**[Eduard Dudar](https://jira.spring.io/secure/ViewProfile.jspa?name=edudar)** opened **[DATACOUCH-647](https://jira.spring.io/browse/DATACOUCH-647?redirect=false)** and commented

My application uses auditing but only for dates via `@CreatedDate` and `@LastModifiedDate`. I don't use `xxxBy` annotations.

With Spring Boot 2.2.x and Spring Data Couchbase 3.x, everything starts and works as expected. Even though [documentation](https://docs.spring.io/spring-data/couchbase/docs/3.2.0.RELEASE/reference/html/#auditing) says that there must be `AuditorAware<T>` bean. `AuditingHandler` uses `Optional` for auditor so this requirement does not seem to be true even in 3.x version.

Now with Spring Boot 2.3 and Spring Data Couchbase 4.x, the said application does not start. First, it complains that `AuditorAware` bean not found. When I define one, it still complains that a bean named exactly `auditorAwareRef` is not found. I don't see anywhere in the [documentation](https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#auditing) such naming requirement. Second, after defining `auditorAwareRef`, it complains that `dataTimeProviderRef` is missing. And similar to the auditor, a bean has to be named exactly. This part is not in the doc at all.

I feel like this is rather a regression, both beans should no be required for an application to start: the auditor is `Optional` and the datatimeprovider defaults to `CurrentDateTimeProvider.INSTANCE`

---
No further details from [DATACOUCH-647](https://jira.spring.io/browse/DATACOUCH-647?redirect=false)

**Comment by mikereiche** [comment]
The bean annotation must have a name attribute that matches, or if it does not have a name attribute, then the method name must match.

`package app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.data.auditing.CurrentDateTimeProvider;
import org.springframework.data.auditing.DateTimeProvider;
import org.springframework.data.couchbase.config.AbstractCouchbaseConfiguration;
import org.springframework.data.couchbase.repository.auditing.EnableCouchbaseAuditing;
import org.springframework.data.couchbase.repository.config.EnableCouchbaseRepositories;
import org.springframework.data.domain.AuditorAware;

import java.util.Optional;

@SpringBootApplication
@EnableCouchbaseRepositories
@EnableCouchbaseAuditing
@EnableConfigurationProperties
public class Application {

    @Bean ( name = "auditorAwareRef")
    AuditorAware<?> auditorAwareRef() {
        // return new NaiveAuditorAware();
        return Optional::empty;
    }

    @Bean
    DateTimeProvider dateTimeProviderRef() {
        return CurrentDateTimeProvider.INSTANCE;
    }

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    /**
     * This class returns a string that represents the current user
     *
     * @author Michael Reiche
     * @since 3.0
     */
     class NaiveAuditorAware implements AuditorAware<String> {

        private Optional<String> auditor = Optional.of("user1");

        @Override
        public Optional<String> getCurrentAuditor() {
            return auditor;
        }

        public void setAuditor(String auditor) {
            this.auditor = Optional.of(auditor);
        }
    }

}`

**Comment by edudar** [comment]
> In the prior version where you did not get an error, the reason is that the default for the bean name was empty, and had to be explicitly set with @EnableCouchbaseAuditing(auditorAwareRef="")

@mikereiche That's not something I do recall. I've been using `@EnableCouchbaseAuditing` without explicit name references for either auditor or datetimeprovider before the migration.

**Comment by mikereiche** [comment]
I tried without setting the attribute in the annotation and it works as you said it did/does. I'll update my earlier comment.
