### ISSUE TITLE
CouchbaseTemplateSupport does not allow a TranslationService bean to be injected [DATACOUCH-652]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#962]
**[jorgerod](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50246)** opened **[DATACOUCH-652](https://jira.spring.io/browse/DATACOUCH-652?redirect=false)** and commented

 

Hi

 I want to customize TranslationService but CouchbaseTemplateSupport creates a new instance of JacksonTranslationService that implements TranslationService.

```java
public CouchbaseTemplateSupport(final CouchbaseConverter converter) {
     this.converter = converter;
     this.mappingContext = converter.getMappingContext();
     this.translationService = new JacksonTranslationService();
}
```

 In my opinion, instead of creating a new instance, it should be allowed to inject  TranslationService bean.

 

TranslationService bean is created at _org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataConfiguration_ 

```java
@Bean
@ConditionalOnMissingBean
TranslationService couchbaseTranslationService() {
     return new JacksonTranslationService();
}
```

---

**Affects:** 4.1.1 (2020.0.1)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-couchbase/pull/294

**Comment by mikereiche** [comment]
this was implemented.
