### ISSUE TITLE
Support for Scope and Collection API Changes [DATACOUCH-655]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#963]
**[Arun Vijayraghavan](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49896)** opened **[DATACOUCH-655](https://jira.spring.io/browse/DATACOUCH-655?redirect=false)** and commented

Not sure if this ticket is needed, but this will stand as a place holder for the API changes w.r.t underlying server specific scopes and collections API Changes.

 

Please feel free to close this ticket if you think this will be taken care by the JAVA SDK

---
No further details from [DATACOUCH-655](https://jira.spring.io/browse/DATACOUCH-655?redirect=false)

**Comment by mikereiche** [comment]
template support for collections was added in https://github.com/spring-projects/spring-data-couchbase/commit/0e8d5a255abbeb0605ab4004be3569feda4c5d2f

**Comment by mikereiche** [comment]
This still needs repository support added.
