### ISSUE TITLE
Durable Writes implementation with CrudRepository [DATACOUCH-657]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#965]
**[freedThoughts](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50737)** opened **[DATACOUCH-657](https://jira.spring.io/browse/DATACOUCH-657?redirect=false)** and commented

+**Requirement**+ : I have my springboot application, using spring-data-couchbase. My application uses CrudRepository for read and write operations.

I wanted my application to write on more that one node before commit; willing to implement MajorityAndPersistToActive Durable writes. 

+**Problem statement**+ **:** +**+ With CrudRepository, I am unable to find any documentation to implement Durable Writes (MajorityAndPersistToActive).

 

+**Ask**+ : Can you advice on -

1) Is it possible to implement Durable write using CrudRepository ?

2) If yes, can you share any documentation Or any sample implementation ?

 

 

 

+**References/ Lib used in application**+ :

JDK = 1.8

springBootVersion = '2.3.3.RELEASE'

org.springframework.data:spring-data-couchbase:4.1.1

com.couchbase.client:java-client:3.0.9

org.springframework.data.repository.CrudRepository

https://docs.couchbase.com/dotnet-sdk/current/concept-docs/durability-replication-failure-considerations.html#durable-writes

---
No further details from [DATACOUCH-657](https://jira.spring.io/browse/DATACOUCH-657?redirect=false)

**Comment by mikereiche** [comment]
on 4.3.0-M3, options can be specified on repositories that extend DynamicProxyable :
```
public interface AirportRepository extends CouchbaseRepository<Airport, String>, DynamicProxyable<AirportRepository> {
```
```
airportRepository.withOptions(UpsertOptions.upsertOptions().durability(...)).save(airport);
```
