### ISSUE TITLE
add support for querydsl [DATACOUCH-658]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#966]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-658](https://jira.spring.io/browse/DATACOUCH-658?redirect=false)** and commented

---
No further details from [DATACOUCH-658](https://jira.spring.io/browse/DATACOUCH-658?redirect=false)

**Comment by mikereiche** [comment]
supported in 4.4.1
