### ISSUE TITLE
Emit event "AfterRead" [DATACOUCH-669]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-couchbase#977]
**[jorgerod](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50246)** opened **[DATACOUCH-669](https://jira.spring.io/browse/DATACOUCH-669?redirect=false)** and commented

Hello

Would it make sense to emit an "AfterRead" event?

For example, we would like to make certain validations after each reading.

 

Thank you

---

**Affects:** 4.1.1 (2020.0.1)

**Comment by mikereiche** [comment]
See the CustomMappingCouchbaseConverter described in https://github.com/spring-projects/spring-data-couchbase/issues/1067 to do validations on reading.  That might be helpful.
