### ISSUE TITLE
QueryMethod.isCollectionQuery() returns false for Flux<T> findByXXX(..., pageRequest) [DATACOUCH-673]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-couchbase#981]
**[Michael Reiche](https://jira.spring.io/secure/ViewProfile.jspa?name=mikereiche)** opened **[DATACOUCH-673](https://jira.spring.io/browse/DATACOUCH-673?redirect=false)** and commented

This is mostly a note to myself -

QueryMethod.isCollectionQuery() returns false for Flux\<T> findByXXX(..., pageRequest)

airportRepository.findAllByIataLikeOrderByIata("S%", pageRequest)

To resolve this, not only does CouchbaseQueryMethod (or ReactiveCouchbaseQueryMethod) need to override isCollectionQuery() :

`@Override`
public boolean isCollectionQuery() {
return (Boolean) this.isCollectionQueryCouchbase.get();
}

But the lazy field from QueryMethod 'isCollectionQuery' should be substituted from a lazy field from [Reactive]CouchbaseQueryMethod

---
No further details from [DATACOUCH-673](https://jira.spring.io/browse/DATACOUCH-673?redirect=false)

**Comment by mikereiche** [comment]
I believe this was fixed in one of the 588 part 1 merge
